Repository void-linux/void-packages, pull requests merged in 2021-02, with the labels that each got.

#27843 New package: jamulus-3.6.2
  srcpkgs/jamulus/template
  srcpkgs/jamulus/update
Labels: new-package

#28401 New package: glab-1.14.0
  srcpkgs/glab/template
Labels: new-package

#21674 gpsbabel: update to 1.7.0.
  srcpkgs/gpsbabel/patches/configure.patch
  srcpkgs/gpsbabel/patches/correctly-read-diff-and-terr-from-geo-format.patch
  srcpkgs/gpsbabel/patches/drop-map.patch
  srcpkgs/gpsbabel/patches/enigma.patch
  srcpkgs/gpsbabel/patches/fix-build.patch
  srcpkgs/gpsbabel/template
Labels: inactive

#28766 apparmor: load profiles in parallel
  srcpkgs/apparmor/template
  srcpkgs/runit-void/files/09-apparmor.sh
Labels: enhancement

#28835 bind: update to 9.16.12.
  common/shlibs
  srcpkgs/bind/template
Labels: help wanted

#22866 New Package: Dwarf-Therapist-41.1.7
  srcpkgs/Dwarf-Therapist/template
Labels: new-package

#29014 New package: pipe-viewer-0.0.7
  srcpkgs/pipe-viewer-gtk
  srcpkgs/pipe-viewer/template
Labels: new-package

#26151 New package: caja-dropbox-1.24.0
  srcpkgs/caja-dropbox/template
  srcpkgs/caja-dropbox/update
Labels: new-package

#26229 New package: vivid-0.6.0
  srcpkgs/vivid/template
Labels: new-package
