Repository void-linux/void-packages, pull requests merged in 2022-06, with the labels that each got.

#37244 New package: walk-1.0.0
  srcpkgs/walk/template
Labels: new-package

#36773 New package: python3-owslib-0.25.0
  srcpkgs/python3-owslib/template
Labels: new-package

#32744 New package: exfatprogs
  srcpkgs/exfatprogs/template
Labels: new-package, Stale

#37443 lighttpd: update to 1.4.65
  srcpkgs/lighttpd/template
Labels: help wanted

#37436 New package: twitch-cli-1.1.6
  srcpkgs/twitch-cli/template
Labels: new-package

#36241 New package: mozjs91-91.7.1
  common/shlibs
  srcpkgs/mozjs91-devel
  srcpkgs/mozjs91/patches/001-fix-soname.patch
  srcpkgs/mozjs91/patches/002-copy-headers.patch
  srcpkgs/mozjs91/patches/003-tests-timeout.patch
  srcpkgs/mozjs91/patches/004-icu-sources-data-py-decouple.patch
  srcpkgs/mozjs91/patches/005-icu-sources-data-write-command-stderr.patch
  srcpkgs/mozjs91/patches/006-emitter.patch
  srcpkgs/mozjs91/patches/007-tests-use-native-temporarydirectory.patch
  srcpkgs/mozjs91/patches/008-init-patch.patch
  srcpkgs/mozjs91/patches/009-sloppy-m4-detection.patch
  srcpkgs/mozjs91/patches/011-failing-tests-ppc64-s390x.patch
  srcpkgs/mozjs91/patches/012-fix-musl.patch
  srcpkgs/mozjs91/patches/013-disable-spidermonkey-jslint.patch
  srcpkgs/mozjs91/patches/014-rust-target.patch
  srcpkgs/mozjs91/patches/015-drop-rustc-validation.patch
  srcpkgs/mozjs91/patches/017-no-lto-readelf.patch
  srcpkgs/mozjs91/patches/MOZ_NO_RUST_LTO.patch
  srcpkgs/mozjs91/patches/fix-i386-fdlibm.patch
  srcpkgs/mozjs91/template
Labels: new-package

#37195 New package: keyd-2.4.0
  srcpkgs/keyd/files/keyd/run
  srcpkgs/keyd/template
Labels: new-package

#35646 libunistring: update to 1.0.
  srcpkgs/libunistring/template
Labels: Stale

#37557 xsm: update to 1.0.5.
  srcpkgs/xsm/template
Labels: needs-testing

#35548 New package: bdfresize-1.5
  srcpkgs/bdfresize/patches/01-ftbfs-gcc4.patch
  srcpkgs/bdfresize/patches/02-minus-sign.patch
  srcpkgs/bdfresize/template
Labels: new-package, Stale

#36124 New package: bkt-0.5.4
  srcpkgs/bkt/template
Labels: new-package

#37631 New package: hunspell-sl_SI-2020.12.31
  srcpkgs/hunspell-sl_SI/template
  srcpkgs/hunspell-sl_SI/update
Labels: new-package

#36054 New package: hblock-3.4.0
  srcpkgs/hblock/template
Labels: new-package

#29593 New package: prs-0.3.2
  srcpkgs/prs-gtk3
  srcpkgs/prs/template
Labels: new-package, Stale

#35874 vkBasalt: update to 0.3.2.5
  srcpkgs/vkBasalt/template
Labels: Stale

#35659 roswell: Reword short description.
  srcpkgs/roswell/template
Labels: Stale

#36128 uhubctl: update to 2.4.0
  srcpkgs/uhubctl/patches/Makefile.patch
  srcpkgs/uhubctl/template
Labels: Stale

#36135 scid_vs_pc: update to 4.23
  srcpkgs/scid_vs_pc/template
Labels: Stale

#36037 New package: japa-0.9.4
  srcpkgs/japa/template
Labels: new-package, Stale

#36019 ddgr: update to 2.0.
  srcpkgs/ddgr/template
Labels: Stale

#37724 gef: update to 2022.06
  srcpkgs/gef/template
Labels: needs-testing

#36235 libepoxy: update to 1.5.10.
  srcpkgs/libepoxy/template
Labels: Stale

#36286 fasm: update to 1.73.30.
  srcpkgs/fasm/template
Labels: Stale
