Repository void-linux/void-packages, pull requests merged in 2022-05, with the labels that each got.

#36654 New package: apcupsd-3.14.14
  srcpkgs/apcupsd/files/apcupsd/run
  srcpkgs/apcupsd/template
Labels: new-package

#27757 New package: paleta
  srcpkgs/paleta/template
Labels: new-package

#33639 New package: activityrelay-0.2.0
  srcpkgs/activityrelay/files/activityrelay/log/run
  srcpkgs/activityrelay/files/activityrelay/run
  srcpkgs/activityrelay/template
  srcpkgs/activityrelay/update
Labels: new-package

#36848 New package: rink-0.6.3
  srcpkgs/rink/template
Labels: new-package

#36947 leftwm: update to 0.3.0
  srcpkgs/leftwm/patches/fix-arm-builds.patch
  srcpkgs/leftwm/patches/series
  srcpkgs/leftwm/template
Labels: help wanted

#29850 New package: mdbook-mermaid-0.10.0
  srcpkgs/mdbook-mermaid/template
Labels: new-package

#36959 New package: got-0.70
  srcpkgs/got/patches/cross.patch
  srcpkgs/got/template
Labels: new-package

#36915 New Package: clickclack-0.2.3
  srcpkgs/clickclack/template
  srcpkgs/clickclack/update
Labels: new-package

#36659 common/hooks/pre-pkg/04-generate-runtime-deps.sh: sort deps for reproducibility
  common/hooks/pre-pkg/04-generate-runtime-deps.sh
Labels: xbps-src

#29492 [WiP] xbps-src/shutils/update_check.sh: change gitlab check to handle subgroups
  common/xbps-src/shutils/update_check.sh
Labels: enhancement

#35831 New package: q5go-2.13
  srcpkgs/q5go/patches/qgo.desktop.patch
  srcpkgs/q5go/template
Labels: new-package

#37174 New package: act-0.2.26
  srcpkgs/act/template
Labels: new-package

#36622 New package: oneko-1.2.5
  srcpkgs/oneko/patches/cursorrecover.diff
  srcpkgs/oneko/patches/fix-warnings.diff
  srcpkgs/oneko/patches/rmshape_fixtypos.diff
  srcpkgs/oneko/template
Labels: new-package

#37013 New package: riff-2.16.2
  srcpkgs/riff/patches/doublebuild.patch
  srcpkgs/riff/template
Labels: new-package

#34591 New package: k3d-5.4.1
  srcpkgs/k3d/template
Labels: new-package

#30524 New package: litecli-1.8.0
  srcpkgs/litecli/template
Labels: new-package
