Repository void-linux/void-packages, pull requests merged in 2022-08, with the labels that each got.

#37819 New package: wayclip-0.3
  srcpkgs/wayclip/template
Labels: new-package

#36905 New package: mercury-22.01_1, mercury-libs-22.01_1, mercury-tools-22.01_1
  srcpkgs/mercury-libs
  srcpkgs/mercury-tools
  srcpkgs/mercury/template
Labels: new-package

#38418 etc/defaults.conf: add XBPS_UPDATE_CHECK_VERBOSE
  etc/defaults.conf
Labels: xbps-src

#38443 xcdroast: remove package
  srcpkgs/removed-packages/template
  srcpkgs/xcdroast/template
Labels: remove

#38441 yabause-gtk: remove package
  srcpkgs/removed-packages/template
  srcpkgs/yabause-gtk/patches/fix-cflags.patch
  srcpkgs/yabause-gtk/patches/rwx.patch
  srcpkgs/yabause-gtk/template
  srcpkgs/yabause-gtk/update
Labels: remove

#38442 xnp2: remove package
  srcpkgs/removed-packages/template
  srcpkgs/xnp2/INSTALL.msg
  srcpkgs/xnp2/patches/define_cplusplus.patch
  srcpkgs/xnp2/template
  srcpkgs/xnp2/update
Labels: remove

#38109 New package: wslu-3.2.4
  srcpkgs/wslu/template
Labels: new-package

#36410 New package: swayimg-1.8
  srcpkgs/swayimg/template
Labels: new-package

#38440 xournal: remove package
  srcpkgs/xournal
  srcpkgs/xournal/template
  srcpkgs/xournalpp/template
Labels: remove

#38495 xarchiver: fix double-clicking regression
  srcpkgs/xarchiver/patches/doubleclick.patch
  srcpkgs/xarchiver/template
Labels: needs-testing

#38522 alarm-clock: remove package
  srcpkgs/alarm-clock/template
  srcpkgs/removed-packages/template
Labels: remove

#26888 New package: cloudflared-2022.7.1
  srcpkgs/cloudflared/template
Labels: new-package

#38531 lighttpd: update to 1.4.66
  srcpkgs/lighttpd/template
Labels: needs-testing

#34721 New package: senpai-0.1.0
  srcpkgs/senpai/template
Labels: new-package

#38564 bff: change distfile
  srcpkgs/bff/template
Labels: remove

#38620 New package: pdf2djvu-0.9.19
  srcpkgs/pdf2djvu/template
Labels: new-package

#38596 pgadmin3: remove package
  srcpkgs/pgadmin3/patches/pgadmin3-fix-segfault.patch
  srcpkgs/pgadmin3/patches/pgadmin3_unbundle-libssh.patch
  srcpkgs/pgadmin3/template
  srcpkgs/removed-packages/template
Labels: remove

#38595 mesa: update to 22.1.6.
  srcpkgs/mesa/template
Labels: needs-testing

#38082 New package: labwc-0.5.3
  srcpkgs/labwc/template
Labels: new-package, needs-testing

#37259 New package: jsonnet-language-server-0.7.2
  srcpkgs/jsonnet-language-server/template
Labels: new-package

#38729 New package: cbonsai-1.3.1
  srcpkgs/cbonsai/template
Labels: new-package

#38667 New package: gnome-software-42.4.
  srcpkgs/gnome-software-devel
  srcpkgs/gnome-software/template
Labels: new-package

#38771 New package: flrig-1.4.7
  srcpkgs/flrig/template
Labels: new-package

#35029 New package: XMousePasteBlock-1.3_1
  srcpkgs/XMousePasteBlock/template
Labels: new-package

#38644 ytop: remove package
  srcpkgs/removed-packages/template
  srcpkgs/ytop/template
Labels: remove

#38666 perl-MIME-Charset: update to 1.013.1
  srcpkgs/perl-MIME-Charset/template
Labels: needs-testing

#37212 minikube: update to 1.25.1.
  srcpkgs/minikube/template
Labels: Stale

#38864 gconfmm: remove package
  common/shlibs
  srcpkgs/gconfmm-devel
  srcpkgs/gconfmm-doc
  srcpkgs/gconfmm/template
  srcpkgs/removed-packages/template
Labels: remove
