Repository void-linux/void-packages, pull requests merged in 2022-04, with the labels that each got.

#36432 emacs-gtk2: remove package
  srcpkgs/emacs-gtk2
  srcpkgs/emacs/template
  srcpkgs/removed-packages/template
Labels: remove

#33632 New package: acme.sh-3.0.2
  srcpkgs/acme.sh/template
Labels: new-package

#32573 New package: LimeSuite-20.10.0
  common/shlibs
  srcpkgs/LimeSuite-devel
  srcpkgs/LimeSuite-doc
  srcpkgs/LimeSuite/template
  srcpkgs/SoapyLMS7
Labels: new-package

#35462 New package: mandown-0.1.2
  srcpkgs/mandown/template
Labels: new-package

#32880 New package: dsda-doom-0.22.5
  srcpkgs/dsda-doom/patches/affinity-hack.patch
  srcpkgs/dsda-doom/template
Labels: new-package

#29907 New package: sigi-3.1.0
  srcpkgs/sigi/template
Labels: new-package

#36069 [RFC]: xbps-src: add strict mode
  common/environment/setup/vsed.sh
  common/travis/build.sh
  xbps-src
Labels: xbps-src

#36443 vala-panel-appmenu: remove gtk2 subpackage
  common/shlibs
  srcpkgs/appmenu-gtk-module
  srcpkgs/removed-packages/template
  srcpkgs/vala-panel-appmenu/template
Labels: remove

#34710 New package: kalendar-0.4.0
  srcpkgs/kalendar/template
Labels: new-package

#34979 New package: PolyMC-1.1.1
  srcpkgs/PolyMC/files/README.voidlinux
  srcpkgs/PolyMC/template
  srcpkgs/PolyMC/update
Labels: new-package

#34878 ruby-build: update to 20211227.
  srcpkgs/ruby-build/template
Labels: Stale

#36458 New package: wireproxy-1.0.1
  srcpkgs/wireproxy/files/wireproxy/run
  srcpkgs/wireproxy/template
Labels: new-package

#35693 New package: cocogitto-5.0.1
  srcpkgs/cocogitto/template
Labels: new-package

#36528 New package: mousai-0.6.6
  srcpkgs/Mousai/template
Labels: new-package

#28785 New package: libgccjit-10.2.1_pre1
  common/shlibs
  srcpkgs/libgccjit-devel
  srcpkgs/libgccjit/files/gccgo-musl.patch
  srcpkgs/libgccjit/files/libgccjit-musl.patch
  srcpkgs/libgccjit/files/libgnarl-musl.patch
  srcpkgs/libgccjit/files/libssp-musl.patch
  srcpkgs/libgccjit/patches
  srcpkgs/libgccjit/template
  srcpkgs/libgccjit/update
Labels: new-package

#34559 xbps-src: make -E ignore remote repositories with -N
  common/xbps-src/shutils/common.sh
  xbps-src
Labels: xbps-src

#20028 New package: uucp-1.07
  srcpkgs/uucp/INSTALL
  srcpkgs/uucp/files/uulog.1
  srcpkgs/uucp/files/uuname.1
  srcpkgs/uucp/files/uupick.1
  srcpkgs/uucp/files/uusched.8
  srcpkgs/uucp/files/uuto.1
  srcpkgs/uucp/patches/compiler-warnings.patch
  srcpkgs/uucp/patches/manpage.patch
  srcpkgs/uucp/patches/no-sleep.patch
  srcpkgs/uucp/patches/option-to-not-force-hw-control.patch
  srcpkgs/uucp/patches/spelling.patch
  srcpkgs/uucp/patches/uucp-alt-misc.patch
  srcpkgs/uucp/patches/uucp-org.patch
  srcpkgs/uucp/patches/wait-for-correct-parent.patch
  srcpkgs/uucp/patches/zpipe-improved-pipe.patch
  srcpkgs/uucp/template
Labels: new-package

#25038 yaboot: fix build w/ gcc10 and host i686/x86_64
  srcpkgs/yaboot/patches/0003-build-system.patch
  srcpkgs/yaboot/template
Labels: Stale

#35661 New package: latexmk-4.76
  srcpkgs/texlive-latexmk
  srcpkgs/texlive/template
Labels: new-package

#36428 cgminer: remove package
  srcpkgs/cgminer/files/cgminer/run
  srcpkgs/cgminer/template
  srcpkgs/removed-packages/template
Labels: remove

#36681 xbps-src: sort and deduplicate packages at update-sys
  common/xbps-src/shutils/bulk.sh
Labels: xbps-src

#32774 hooks/99-pkglint.sh: make missing shlib entry not a warning
  common/hooks/pre-pkg/99-pkglint.sh
Labels: xbps-src

#36830 xbps-src: add flag to build broken packages
  common/xbps-src/shutils/common.sh
  common/xbps-src/shutils/pkgtarget.sh
  xbps-src
Labels: xbps-src
