Repository void-linux/void-packages, pull requests merged in 2022-10, with the labels that each got.

#39561 Pyrex: remove package.
  srcpkgs/Pyrex/template
  srcpkgs/removed-packages/template
Labels: remove

#39588 empathy: remove package
  srcpkgs/empathy/files/README.voidlinux
  srcpkgs/empathy/patches/enchant-2.patch
  srcpkgs/empathy/template
  srcpkgs/removed-packages/template
Labels: remove

#39587 FeedReader: remove package
  srcpkgs/FeedReader/files/fix-FeedServerMain_vala.patch
  srcpkgs/FeedReader/template
  srcpkgs/removed-packages/template
Labels: remove

#37715 New package: arti-1.0.0
  srcpkgs/arti/template
  srcpkgs/arti/update
Labels: new-package

#39316 New package: epy-2022.4.18
  srcpkgs/epy/template
Labels: new-package

#37465 New package: taplo-0.7.0
  srcpkgs/taplo/template
Labels: new-package

#39684 zfs: update to 2.1.6.
  srcpkgs/zfs/template
Labels: hacktoberfest-accepted

#39738 New package: wired-notify-0.10.2
  srcpkgs/wired-notify/patches/32bit.patch
  srcpkgs/wired-notify/patches/crossbeam-utils_update.patch
  srcpkgs/wired-notify/template
Labels: new-package

#39711 searchfile: remove package
  srcpkgs/removed-packages/template
  srcpkgs/searchfile/template
Labels: remove

#39847 go-langserver: remove package
  srcpkgs/go-langserver/template
  srcpkgs/removed-packages/template
Labels: remove

#39307 New package: zr-1.0.2
  srcpkgs/zr/template
Labels: new-package

#38719 New package: tlpui-1.5.0.5
  srcpkgs/tlpui/template
Labels: new-package

#39919 julia: remove
  srcpkgs/julia/patches/julia-hardcoded-libs.patch
  srcpkgs/julia/template
  srcpkgs/removed-packages/template
Labels: remove

#39942 [wip] New package: linux6.0-6.0.1
  srcpkgs/linux6.0-dbg
  srcpkgs/linux6.0-headers
  srcpkgs/linux6.0/files/arm64-dotconfig
  srcpkgs/linux6.0/files/i386-dotconfig
  srcpkgs/linux6.0/files/mv-debug
  srcpkgs/linux6.0/files/ppc-dotconfig
  srcpkgs/linux6.0/files/ppc64-dotconfig
  srcpkgs/linux6.0/files/ppc64le-dotconfig
  srcpkgs/linux6.0/files/x86_64-dotconfig
  srcpkgs/linux6.0/patches/fix-musl-objtool.patch
  srcpkgs/linux6.0/patches/musl-speakup.patch
  srcpkgs/linux6.0/patches/ppc-vas-on-4k.patch
  srcpkgs/linux6.0/patches/ppc64-be-elfv2.patch
  srcpkgs/linux6.0/template
Labels: new-package

#39922 New package: qodem-1.0.1
  srcpkgs/qodem/template
Labels: new-package

#39949 New package: superd-0.7
  srcpkgs/superd/patches/add-installmisc-target.patch
  srcpkgs/superd/template
Labels: new-package

#39986 Lidarr: remove package
  srcpkgs/Lidarr/files/Lidarr/log/run
  srcpkgs/Lidarr/files/Lidarr/run
  srcpkgs/Lidarr/files/lidarr
  srcpkgs/Lidarr/template
  srcpkgs/removed-packages/template
Labels: remove

#39754 New Package: citations-0.5.1
  srcpkgs/citations/template
Labels: new-package

#40072 escrotum: remove package
  srcpkgs/escrotum/template
  srcpkgs/removed-packages/template
Labels: remove

#40074 celestia-gtk: remove package
  srcpkgs/celestia-gtk/patches/NULL_notdecleared.patch
  srcpkgs/celestia-gtk/patches/Z_BEST_COMPRESSION.patch
  srcpkgs/celestia-gtk/patches/fix-stdint_redefine.patch
  srcpkgs/celestia-gtk/patches/memcpy_notdecleared.patch
  srcpkgs/celestia-gtk/patches/missing_mathlib.patch
  srcpkgs/celestia-gtk/template
  srcpkgs/celestia-gtk/update
  srcpkgs/removed-packages/template
Labels: remove

#40015 xbps-src: don't use deprecated egrep
  common/xbps-src/shutils/build_dependencies.sh
Labels: xbps-src

#38209 python3-pyperclip: update to 1.8.2.
  srcpkgs/python3-pyperclip/template
Labels: Stale

#27399 New package: rsv-1.3.3
  srcpkgs/rsv/template
Labels: new-package, Stale

#40115 New package: dotool-1.0
  srcpkgs/dotool/files/dotoold/log/run
  srcpkgs/dotool/files/dotoold/run
  srcpkgs/dotool/template
Labels: new-package

#38430 New package: zanshin-22.08.2
  srcpkgs/zanshin/template
Labels: new-package

#38388 New package: kwave-22.08.2
  srcpkgs/kwave/template
Labels: new-package

#38423 New package: sweeper-22.08.2
  srcpkgs/sweeper/template
Labels: new-package

#38428 New package: lokalize-22.08.2
  srcpkgs/lokalize/template
Labels: new-package

#40116 distcc: remove distcc-gtk subpackage
  srcpkgs/distcc-gtk
  srcpkgs/distcc/template
  srcpkgs/removed-packages/template
Labels: remove
