Repository void-linux/void-packages, pull requests merged in 2022-11, with the labels that each got.

#38406 New package: openpgp-card-tools-0.9.0
  srcpkgs/openpgp-card-tools/template
  srcpkgs/openpgp-card-tools/update
Labels: new-package

#40265 New package: cargo-auditable-0.5.2
  srcpkgs/cargo-auditable/template
Labels: new-package

#37147 New package: direwolf-1.6
  srcpkgs/direwolf/patches/fix_desktop.patch
  srcpkgs/direwolf/patches/fix_musl.patch
  srcpkgs/direwolf/patches/fix_scripts_install.patch
  srcpkgs/direwolf/patches/fix_udev_install.patch
  srcpkgs/direwolf/template
Labels: new-package

#40236 rtl8822bu-dkms: update to 20221030.
  srcpkgs/rtl8822bu-dkms/patches/0001-void-arch-generic-plumbing-bits.patch
  srcpkgs/rtl8822bu-dkms/template
Labels: needs-testing

#40051 New package: python3-pygit2-1.10.1
  srcpkgs/python3-pygit2/template
Labels: new-package

#40316 New package: lite-xl-2.1.0
  srcpkgs/lite-xl/template
Labels: new-package

#40464 plex-media-server: remove package
  srcpkgs/plex-media-server/files/LICENSE
  srcpkgs/plex-media-server/files/default
  srcpkgs/plex-media-server/files/plex-media-server/run
  srcpkgs/plex-media-server/files/start_pms
  srcpkgs/plex-media-server/template
  srcpkgs/removed-packages/template
Labels: remove

#40512 plex-media-player: remove package
  srcpkgs/plex-media-player/patches/fix-opengl-cb-api-usage.patch
  srcpkgs/plex-media-player/patches/qt5-append-header.patch
  srcpkgs/plex-media-player/template
  srcpkgs/plex-media-player/update
  srcpkgs/removed-packages/template
Labels: remove

#39971 New package: diffuse-0.7.5
  srcpkgs/diffuse/template
Labels: new-package

#40563 gtk-sharp2: remove package
  srcpkgs/gtk-sharp2/patches/ftbfs.patch
  srcpkgs/gtk-sharp2/template
  srcpkgs/removed-packages/template
Labels: remove

#36903 New package: wezterm-20220905_1
  srcpkgs/wezterm-terminfo
  srcpkgs/wezterm/patches/0001-32bit.patch
  srcpkgs/wezterm/patches/0002-remove-distro-fonts.patch
  srcpkgs/wezterm/patches/remove-libgit.patch
  srcpkgs/wezterm/template
  srcpkgs/wezterm/update
Labels: new-package

#39917 mod_wsgi: update to 4.9.4, fixes build with Python 3.10
  srcpkgs/mod_wsgi/INSTALL.msg
  srcpkgs/mod_wsgi/patches/cross-python.patch
  srcpkgs/mod_wsgi/template
Labels: needs-testing

#39498 New package: mozjs102-102.3.0
  common/shlibs
  srcpkgs/mozjs102-devel
  srcpkgs/mozjs102/patches/001-fix-soname.patch
  srcpkgs/mozjs102/patches/002-copy-headers.patch
  srcpkgs/mozjs102/patches/003-tests-timeout.patch
  srcpkgs/mozjs102/patches/004-icu-sources-data-py-decouple.patch
  srcpkgs/mozjs102/patches/005-icu-sources-data-write-command-stderr.patch
  srcpkgs/mozjs102/patches/006-emitter.patch
  srcpkgs/mozjs102/patches/007-tests-use-native-temporarydirectory.patch
  srcpkgs/mozjs102/patches/008-init-patch.patch
  srcpkgs/mozjs102/patches/009-sloppy-m4-detection.patch
  srcpkgs/mozjs102/patches/011-failing-tests-ppc64-s390x.patch
  srcpkgs/mozjs102/patches/012-fix-musl.patch
  srcpkgs/mozjs102/patches/013-disable-spidermonkey-jslint.patch
  srcpkgs/mozjs102/patches/014-rust-target.patch
  srcpkgs/mozjs102/patches/015-drop-rustc-validation.patch
  srcpkgs/mozjs102/patches/017-no-lto-readelf.patch
  srcpkgs/mozjs102/patches/MOZ_NO_RUST_LTO.patch
  srcpkgs/mozjs102/patches/armv6l-isb.patch
  srcpkgs/mozjs102/patches/fix-build-ppc32.patch
  srcpkgs/mozjs102/patches/fix-i386-fdlibm.patch
  srcpkgs/mozjs102/patches/python-3.11.patch
  srcpkgs/mozjs102/template
  srcpkgs/mozjs102/update
Labels: new-package

#40346 hooks/99-pkglint.sh: error when pkg ships gschemas.compiled
  common/hooks/pre-pkg/99-pkglint.sh
Labels: xbps-src

#40755 compton-conf: remove package
  srcpkgs/compton-conf/template
  srcpkgs/removed-packages/template
Labels: remove

#40726 New package: qsv-0.70.0.
  srcpkgs/qsv/template
Labels: new-package

#40737 New package: streampager-0.10.2
  srcpkgs/streampager/template
Labels: new-package

#38971 common/xbps-src/shutils/update_check.sh: ignore pkgs without distfiles
  common/xbps-src/shutils/update_check.sh
Labels: xbps-src

#40412 gen-runtime-deps: verify rdeps for shlib_requires too
  common/hooks/pre-pkg/04-generate-runtime-deps.sh
Labels: xbps-src
