Repository void-linux/void-packages, pull requests merged in 2022-09, with the labels that each got.

#38974 adobe-flash-plugin: remove package.
  srcpkgs/adobe-flash-plugin-ppapi
  srcpkgs/adobe-flash-plugin/files/flash-plugin-ppapi.sh
  srcpkgs/adobe-flash-plugin/template
  srcpkgs/removed-packages/template
Labels: remove

#38937 exfat-dkms: remove package
  srcpkgs/exfat-dkms/patches/linux4.18.patch
  srcpkgs/exfat-dkms/template
Labels: remove

#39065 ocaml-lablgtk2: remove package
  srcpkgs/ocaml-lablgtk2-gnomecanvas
  srcpkgs/ocaml-lablgtk2-gtksourceview2
  srcpkgs/ocaml-lablgtk2-gtkspell
  srcpkgs/ocaml-lablgtk2/template
  srcpkgs/ocaml-lablgtk2/update
  srcpkgs/removed-packages/template
Labels: remove

#38478 git-secret: update to 0.5.0.
  srcpkgs/git-secret/template
Labels: needs-testing

#35527 New package: power-profiles-daemon-0.12
  srcpkgs/power-profiles-daemon/files/power-profiles-daemon/run
  srcpkgs/power-profiles-daemon/template
Labels: new-package

#34073 New package: helden-software-5.5.3
  srcpkgs/helden-software/patches/0001-fix-file-locations.patch
  srcpkgs/helden-software/patches/0002-translate-comment.patch
  srcpkgs/helden-software/template
Labels: new-package, Stale

#38935 C{,XX}FLAGS: change -fdebug-prefix-map for cmake and meson
  common/environment/configure/debug-debug-prefix-map.sh
Labels: xbps-src

#37983 New package: iaito-5.7.2
  srcpkgs/iaito/template
Labels: new-package

#34451 dma: fix /etc/dma/*.conf permissions
  srcpkgs/dma/INSTALL
  srcpkgs/dma/template
Labels: Stale

#39170 raul: remove package
  common/shlibs
  srcpkgs/raul-devel
  srcpkgs/raul/template
  srcpkgs/removed-packages/template
Labels: remove

#39167 New package: mujs-1.2.0
  srcpkgs/mujs/template
Labels: new-package

#32760 New package: cargo-update-8.1.4
  srcpkgs/cargo-update/template
Labels: new-package, Stale

#39348 New package: rust-bindgen-0.60.1
  srcpkgs/rust-bindgen/template
Labels: new-package

#37912 new package: sioyek
  srcpkgs/sioyek/patches/294.patch
  srcpkgs/sioyek/template
Labels: new-package

#39459 getmail: remove package
  srcpkgs/getmail/template
  srcpkgs/getmail/update
  srcpkgs/removed-packages/template
Labels: remove

#39461 miro-video-converter: remove package
  srcpkgs/miro-video-converter/template
  srcpkgs/removed-packages/template
Labels: remove

#39458 couchpotato: remove package
  srcpkgs/couchpotato/files/couchpotato/run
  srcpkgs/couchpotato/template
  srcpkgs/couchpotato/update
  srcpkgs/removed-packages/template
Labels: remove

#39460 mimms: remove package
  srcpkgs/mimms/template
  srcpkgs/removed-packages/template
Labels: remove

#39332 lighttpd: update to 1.4.67
  srcpkgs/lighttpd/template
Labels: needs-testing

#37700 xbps-src: add update-local and show-local-updates
  common/xbps-src/shutils/bulk.sh
  xbps-src
Labels: xbps-src, Stale

#37760 New package: chathistorysync-0.1.0
  srcpkgs/chathistorysync/template
Labels: new-package, Stale
