Repository void-linux/void-packages, pull requests merged in 2022-07, with the labels that each got.

#36716 New package: hut-0.1.0
  srcpkgs/hut/template
Labels: new-package

#34093 gmic: fix license, clean do_build
  srcpkgs/gmic/patches/01-includedir.patch
  srcpkgs/gmic/patches/02-opt-flags.patch
  srcpkgs/gmic/patches/03-plugindir-and-no-wget.patch
  srcpkgs/gmic/patches/04-no-krita-and-order.patch
  srcpkgs/gmic/template
Labels: Stale

#35855 gsmartcontrol: update to 1.1.4.
  srcpkgs/gsmartcontrol/files/README.voidlinux
  srcpkgs/gsmartcontrol/template
Labels: Stale

#37807 New package: xfce4-datetime-plugin-0.8.1
  srcpkgs/xfce4-datetime-plugin/template
Labels: new-package

#36910 New package: wvkbd-0.8.2
  srcpkgs/wvkbd/template
Labels: new-package

#36189 lazygit: update to 0.34
  srcpkgs/lazygit/template
Labels: Stale

#37821 protonmail-bridge: update to 2.1.3.
  srcpkgs/protonmail-bridge/template
Labels: needs-testing

#37806 New package: aspell-it-2.2_20050523-0
  srcpkgs/aspell-it/template
Labels: new-package

#37858 libinput: update to 1.21.0.
  srcpkgs/libinput/template
Labels: needs-testing

#37840 pipewire: update to 0.3.54
  srcpkgs/pipewire/template
Labels: needs-testing

#37992 New package: Swapspace-1.17
  srcpkgs/Swapspace/files/swapspace/run
  srcpkgs/Swapspace/template
Labels: new-package

#38040 pipewire: update to 0.3.55
  srcpkgs/pipewire/patches/0.3.55-jack-mix.patch
  srcpkgs/pipewire/template
Labels: needs-testing

#37694 New package: lua-language-server-3.5.0
  srcpkgs/lua-language-server/files/lua-language-server
  srcpkgs/lua-language-server/patches/enable-cross-compilation.patch
  srcpkgs/lua-language-server/template
Labels: new-package

#38212 New package: python3-shellingham-1.4.0
  srcpkgs/python3-shellingham/template
Labels: new-package

#38156 New package: uacme-1.7.1
  srcpkgs/uacme/template
Labels: new-package

#38247 New package: gnome-browser-connector-42.0
  srcpkgs/chrome-gnome-shell
  srcpkgs/chrome-gnome-shell/template
  srcpkgs/chrome-gnome-shell/update
  srcpkgs/gnome-browser-connector/template
Labels: new-package

#38217 pipewire: update to 0.3.56.
  srcpkgs/pipewire/patches/0.3.55-jack-mix.patch
  srcpkgs/pipewire/template
Labels: needs-testing

#38377 New package: kasts-22.06
  srcpkgs/kasts/template
Labels: new-package
