Repository void-linux/void-packages, pull requests merged in 2022-12, with the labels that each got.

#40359 env/setup/sourcepkg: unset all exported variables
  common/environment/setup/sourcepkg.sh
Labels: xbps-src

#40813 New package: libdrm-test-progs-2.4.113
  common/shlibs
  srcpkgs/libdrm-test-progs
  srcpkgs/libdrm/template
Labels: new-package

#40588 New package: qprompt-1.1.2
  srcpkgs/qprompt/template
Labels: new-package

#40701 New package: gcr4-4.0.0
  common/shlibs
  srcpkgs/gcr4-devel
  srcpkgs/gcr4/template
  srcpkgs/gcr4/update
Labels: new-package

#40584 New package: bismuth-3.1.4
  srcpkgs/bismuth/template
Labels: new-package

#40929 racer: remove package
  srcpkgs/racer/template
  srcpkgs/racer/update
Labels: remove

#41032 common/xbps-src/shutils/show.sh: make show display consistent
  common/xbps-src/shutils/show.sh
Labels: xbps-src

#41194 New package: python3-pyclipper-1.3.0.post4
  srcpkgs/python3-pyclipper/template
Labels: new-package

#36967 New package: imhex-1.25.0
  srcpkgs/imhex-patterns
  srcpkgs/imhex/patches/cross.patch
  srcpkgs/imhex/patches/musl.patch
  srcpkgs/imhex/patches/no-update-check.patch
  srcpkgs/imhex/template
Labels: new-package

#41153 New package: python3-openai-0.25.0
  srcpkgs/python3-openai/template
Labels: new-package

#39445 CKAN: update to 1.31.2
  srcpkgs/CKAN/template
Labels: Stale

#41168 ccache: update to 4.7.4.
  srcpkgs/ccache/files/ccache.1
  srcpkgs/ccache/template
Labels: core

#41337 linux5.15+: Add landlock to CONFIG_LSM
  srcpkgs/linux5.15/files/arm64-dotconfig
  srcpkgs/linux5.15/files/i386-dotconfig
  srcpkgs/linux5.15/files/ppc-dotconfig
  srcpkgs/linux5.15/files/ppc64-dotconfig
  srcpkgs/linux5.15/files/ppc64le-dotconfig
  srcpkgs/linux5.15/files/x86_64-dotconfig
  srcpkgs/linux6.0/files/arm64-dotconfig
  srcpkgs/linux6.0/files/i386-dotconfig
  srcpkgs/linux6.0/files/ppc-dotconfig
  srcpkgs/linux6.0/files/ppc64-dotconfig
  srcpkgs/linux6.0/files/ppc64le-dotconfig
  srcpkgs/linux6.0/files/x86_64-dotconfig
  srcpkgs/linux6.1/files/arm64-dotconfig
  srcpkgs/linux6.1/files/i386-dotconfig
  srcpkgs/linux6.1/files/ppc-dotconfig
  srcpkgs/linux6.1/files/ppc64-dotconfig
  srcpkgs/linux6.1/files/ppc64le-dotconfig
  srcpkgs/linux6.1/files/x86_64-dotconfig
Labels: needs-testing, core

#41317 btrfs-progs: update to 6.1.
  srcpkgs/btrfs-progs/patches/fix-the-uuid-report-in-btrfs-subvolume-list--u.patch
  srcpkgs/btrfs-progs/template
Labels: core
