Repository void-linux/void-packages, pull requests merged in 2023-07, with the labels that each got.

#43906 New package: juliaup-1.8.16
  srcpkgs/juliaup/template
Labels: new-package

#43097 New package: darkman-1.5.4
  srcpkgs/darkman/template
Labels: new-package

#44929 chroot-curl: Remove.
  srcpkgs/chroot-curl
  srcpkgs/curl/template
Labels: remove

#43082 cross-arm-none-eabi-gdb: update to 13.2
  srcpkgs/cross-arm-none-eabi-gdb/template
Labels: Stale

#44855 New package: autofirma-1.8.2
  srcpkgs/autofirma/files/autofirma
  srcpkgs/autofirma/template
Labels: new-package

#44952 New package: maddy-0.7.0.
  srcpkgs/maddy/files/maddy/run
  srcpkgs/maddy/template
Labels: new-package

#44687 New package: lemoa-0.2.0
  srcpkgs/lemoa/template
Labels: new-package

#44959 New package: spacenavd-1.2-1
  srcpkgs/spacenavd/files/spacenavd/run
  srcpkgs/spacenavd/template
Labels: new-package

#44971 New package: spnavcfg-1.1-1
  srcpkgs/spnavcfg/template
Labels: new-package

#44655 nvidia470: update to 470.199.02.
  srcpkgs/nvidia470/patches/linux-6.3.patch
  srcpkgs/nvidia470/template
Labels: needs-testing

#43635 New package: furnace-0.6pre7
  srcpkgs/furnace/template
Labels: new-package

#45059 make: update to 4.4.1.
  srcpkgs/make/patches/regression-openjdk9.patch
  srcpkgs/make/template
Labels: core

#45058 New package: kaboom-0.1.0
  srcpkgs/kaboom/template
Labels: new-package

#44663 xbps-src: new vopt_feature helper
  Manual.md
  common/environment/setup/options.sh
Labels: xbps-src

#45293 PolyMC: drop package
  srcpkgs/PolyMC
  srcpkgs/PrismLauncher/template
  srcpkgs/removed-packages/template
Labels: remove

#45219 tar: update to 1.35.
  srcpkgs/tar/patches/cve-2022-48303.patch
  srcpkgs/tar/template
Labels: core

#45299 New package: linux6.4-6.4.7
  srcpkgs/linux6.4-dbg
  srcpkgs/linux6.4-headers
  srcpkgs/linux6.4/files/arm64-dotconfig
  srcpkgs/linux6.4/files/i386-dotconfig
  srcpkgs/linux6.4/files/mv-debug
  srcpkgs/linux6.4/files/x86_64-dotconfig
  srcpkgs/linux6.4/patches/fix-musl-objtool.patch
  srcpkgs/linux6.4/patches/fixdep-largefile.patch
  srcpkgs/linux6.4/template
Labels: new-package
