Repository void-linux/void-packages, pull requests merged in 2023-11, with the labels that each got.

#44823 New package: rio-0.0.26
  srcpkgs/rio-terminfo
  srcpkgs/rio/template
Labels: new-package

#45580 xbps-src: add default build option description
  common/xbps-src/shutils/show.sh
Labels: xbps-src, Stale

#47291 common/xbps-src/shutils/chroot.sh: support importing other keys
  .gitignore
  README.md
  common/xbps-src/shutils/chroot.sh
Labels: xbps-src

#45462 common/build-helper/rust.sh: link to libgit2 and libsqlite3 dynamically
  common/build-helper/rust.sh
Labels: xbps-src

#47460 build-helper/rust.sh: prevent stripping by cargo
  common/build-helper/rust.sh
Labels: xbps-src

#47430 New package: typstfmt-0.2.6
  srcpkgs/typstfmt/template
Labels: new-package
