Repository void-linux/void-packages, pull requests merged in 2023-04, with the labels that each got.

#41442 gtick: remove package
  srcpkgs/gtick/template
  srcpkgs/removed-packages/template
Labels: remove, Stale

#43239 New package: lychee-0.11.1
  srcpkgs/lychee/template
Labels: new-package

#43061 new package: tinyramfs
  srcpkgs/tinyramfs/files/config
  srcpkgs/tinyramfs/files/kernel-hook-postinst
  srcpkgs/tinyramfs/files/kernel-hook-postrm
  srcpkgs/tinyramfs/template
Labels: new-package

#38917 New package: drivestrike-2.1.20
  srcpkgs/drivestrike/files/LICENSE
  srcpkgs/drivestrike/files/drivestrike/run
  srcpkgs/drivestrike/template
  srcpkgs/drivestrike/update
Labels: new-package

#43304 common/travis: make check-install use new rootdir.
  common/travis/check-install.sh
Labels: xbps-src

#43320 shutils/build_dependencies.sh: print "with" before build style/helper names
  common/xbps-src/shutils/build_dependencies.sh
Labels: xbps-src

#43418 runit: add chpst -C patch
  srcpkgs/runit/patches/chpst-pwd.patch
  srcpkgs/runit/template
Labels: core

#43431 runit-void: update to 20230413.
  srcpkgs/runit-void/template
Labels: core

#41789 musl-legacy-compat: update to 0.6.
  srcpkgs/musl-legacy-compat/files/tree.h
  srcpkgs/musl-legacy-compat/template
Labels: Stale

#43356 btrfs-progs: update to 6.2.2.
  srcpkgs/btrfs-progs/template
Labels: core

#43279 curl: update to 8.0.1.
  srcpkgs/curl/patches/cfilter-first-non-connected.patch
  srcpkgs/curl/patches/typecheck-expression.patch
  srcpkgs/curl/template
Labels: core

#43590 mpir: remove package
  common/shlibs
  srcpkgs/mpir-devel
  srcpkgs/mpir/template
  srcpkgs/mpir/update
  srcpkgs/removed-packages/template
Labels: remove

#43610 New package: void-repo-bootstrap-1
  srcpkgs/void-repo-bootstrap/template
Labels: new-package

#41885 New package: sdunpack-0.3.0
  srcpkgs/sdunpack/template
Labels: new-package, Stale

#41881 New package: handlr-0.6.4
  srcpkgs/handlr/template
Labels: new-package, Stale

#42379 New package: mpvpaper-1.3
  srcpkgs/mpvpaper/template
Labels: new-package

#43516 linux-firmware: move all mediatek WLAN/BT drivers to -network subpkg
  srcpkgs/linux-firmware/template
Labels: core
