Repository void-linux/void-packages, pull requests merged in 2023-06, with the labels that each got.

#42217 zstd: update to 1.5.5.
  srcpkgs/zstd/template
Labels: core

#42232 New package: muon-0.2.0
  srcpkgs/muon/template
Labels: new-package

#42687 jamulus: update to 3.9.1
  srcpkgs/jamulus/template
Labels: Stale

#44305 zfs: update to 2.1.12.
  srcpkgs/zfs/template
Labels: needs-testing, core

#43882 openlierox: remove package
  srcpkgs/openlierox/patches/fix-cflags.patch
  srcpkgs/openlierox/patches/ppc-musl.patch
  srcpkgs/openlierox/template
  srcpkgs/openlierox/update
  srcpkgs/removed-packages/template
Labels: remove

#43883 libproxy: move to python3
  srcpkgs/libproxy-python3
  srcpkgs/libproxy/template
  srcpkgs/removed-packages/template
Labels: remove

#44373 New package: wlrctl-0.2.2
  srcpkgs/wlrctl/patches/fix-ascii-check.patch
  srcpkgs/wlrctl/template
Labels: new-package

#44210 New package: linux-wifi-hotspot-4.5.0
  srcpkgs/linux-wifi-hotspot/patches/makefile.patch
  srcpkgs/linux-wifi-hotspot/template
Labels: new-package

#44495 common: remove unused python-module build style
  Manual.md
  common/build-style/python-module.sh
  common/environment/build-style/python-module.sh
Labels: xbps-src

#43295 New package: stc-1.4
  srcpkgs/stc/template
Labels: new-package

#43947 New package: gargoyle-2023.1
  srcpkgs/gargoyle/template
Labels: new-package

#43734 New package: a4-0.2.1
  srcpkgs/a4/template
Labels: new-package

#42866 bind-utils: move nsupdate from bind to bind-utils
  srcpkgs/bind/template
Labels: Stale

#42776 kapow: update to 1.6.1.
  srcpkgs/kapow/template
Labels: Stale

#42998 New package: newsraft-0.17
  srcpkgs/newsraft/template
Labels: new-package

#44584 New package: wtfutil-0.43.0
  srcpkgs/wtfutil/template
Labels: new-package

#40378 New package: drm_info-2.4.0
  srcpkgs/drm_info/template
Labels: new-package

#43666 New package: n-9.1.0
  srcpkgs/n/files/README.voidlinux
  srcpkgs/n/template
Labels: new-package

#43653 New package: mmv-go 0.1.6
  srcpkgs/mmv-go/template
Labels: new-package

#43523 New package: solo2-cli-0.2.2
  srcpkgs/solo2-cli/template
Labels: new-package

#43542 New package: zls-0.10.0
  srcpkgs/zls/template
Labels: new-package

#43548 New package: way-displays-1.7.1
  srcpkgs/way-displays/template
Labels: new-package

#38488 New package: sheldon-0.7.3
  srcpkgs/sheldon/template
Labels: new-package

#36329 New package: ansifilter-2.18
  srcpkgs/ansifilter/template
Labels: new-package

#35271 New package: keynav-0.0.20180821
  srcpkgs/keynav/patches/fix-cursor-passthrough.patch
  srcpkgs/keynav/patches/fix-overlapping-screens.patch
  srcpkgs/keynav/template
Labels: new-package

#39181 New package: lesspass-10.2.1
  srcpkgs/lesspass/template
Labels: new-package

#39370 New package: selene-0.25.0
  srcpkgs/selene/template
Labels: new-package

#41355 new package: lapce
  srcpkgs/lapce/patches/desktop-icon.patch
  srcpkgs/lapce/template
  srcpkgs/lapce/update
Labels: new-package

#41166 New package: shotgun-2.5.0
  srcpkgs/shotgun/template
Labels: new-package

#40893 New package: system-monitoring-center 2.14.0
  srcpkgs/system-monitoring-center/template
Labels: new-package

#40693 new package: xosd-2.2.14
  srcpkgs/xosd/template
Labels: new-package

#40392 New package: mazter-0.4.1
  srcpkgs/mazter/template
Labels: new-package

#40216 New package: pinentry-bemenu-0.12.0
  common/shlibs
  srcpkgs/pinentry-bemenu/template
Labels: new-package

#40111 New package: nwg-look-0.2.2
  srcpkgs/nwg-look/template
Labels: new-package

#39907 New package: xone-0.3
  srcpkgs/xone/files/README.voidlinux
  srcpkgs/xone/template
Labels: new-package

#39903 New package: nextdns-1.39.4
  srcpkgs/nextdns/files/nextdns/run
  srcpkgs/nextdns/patches/Don't touch files managed by xbps.patch
  srcpkgs/nextdns/template
Labels: new-package

#41310 New package: flavours-0.6.1
  srcpkgs/flavours/template
Labels: new-package

#42637 New package: ferium-4.4.0
  srcpkgs/ferium/template
Labels: new-package

#42508 New package: hg-evolve-11.0.1
  srcpkgs/hg-evolve/template
Labels: new-package

#41927 New package: hurl-3.0.0
  srcpkgs/hurl/template
Labels: new-package

#41590 New package: taskwarrior-tui-0.23.7
  srcpkgs/taskwarrior-tui/template
Labels: new-package

#42258 rabbitmq-c: update to 0.13.0
  srcpkgs/rabbitmq-c/patches/test.patch
  srcpkgs/rabbitmq-c/template
Labels: needs-testing

#41314 New package: outguess-0.4
  srcpkgs/outguess/template
Labels: new-package

#37478 scryer-prolog: update to 0.9.1
  srcpkgs/scryer-prolog/template
Labels: Stale

#44332 New package: osc-1.1.4
  srcpkgs/osc/template
Labels: new-package

#44246 new package: yaydl-0.13.0
  srcpkgs/yaydl/template
Labels: new-package

#44221 New package: podman-tui-0.9.1
  srcpkgs/podman-tui/template
Labels: new-package

#44058 New package: shortwave-3.2.0
  srcpkgs/shortwave/patches/no-git.patch
  srcpkgs/shortwave/template
Labels: new-package

#44057 New package: amberol-0.10.3
  srcpkgs/amberol/template
Labels: new-package

#44223 New package: adguardian-1.3.0
  srcpkgs/adguardian/template
Labels: new-package

#44023 New package: babelfish-1.1.0
  srcpkgs/babelfish/template
Labels: new-package

#43825 New package: kamera-23.04.0
  srcpkgs/kamera/template
Labels: new-package

#43751 New package: cargo-modules-0.8.0
  srcpkgs/cargo-modules/template
Labels: new-package

#43720 python3-mpv: update to 1.0.3
  srcpkgs/python3-mpv/template
Labels: needs-testing

#44140 New package: eludris-0.3.3
  srcpkgs/eludris/template
  srcpkgs/eludris/update
Labels: new-package

#43494 New package: linuxwave-0.1.3
  srcpkgs/linuxwave/template
Labels: new-package

#43440 New package: frobby-0.9.5
  srcpkgs/frobby-devel
  srcpkgs/frobby/patches/Makefile.patch
  srcpkgs/frobby/template
Labels: new-package

#43423 New package: rtx-1.32.0
  srcpkgs/rtx/template
Labels: new-package

#43411 New package: memray-1.7.0
  srcpkgs/memray/template
Labels: new-package

#43315 New package: swayfx
  srcpkgs/swayfx/INSTALL
  srcpkgs/swayfx/patches/7326.diff
  srcpkgs/swayfx/template
Labels: new-package

#43155 New package: skate-0.2.2
  srcpkgs/skate/template
Labels: new-package

#43045 New package: clifm-1.11
  srcpkgs/clifm/template
Labels: new-package

#43023 New package: rinstall-0.2.0
  srcpkgs/rinstall/template
Labels: new-package

#43142 new package: moar
  srcpkgs/moar/template
Labels: new-package

#42909 New package: zet-1.0.0
  srcpkgs/zet/template
Labels: new-package

#42731 New package: offpunk-1.9.2
  srcpkgs/offpunk/template
Labels: new-package, Stale

#42666 virtuoso: update to 7.2.10
  srcpkgs/virtuoso/patches/always-ieee-floats.patch
  srcpkgs/virtuoso/patches/disable-tgraphql-test.patch
  srcpkgs/virtuoso/patches/fix-utf8-bittest.patch
  srcpkgs/virtuoso/patches/musl-page_size.patch
  srcpkgs/virtuoso/patches/remove-openssl-version-check.patch
  srcpkgs/virtuoso/patches/ssl-connect-state.patch
  srcpkgs/virtuoso/patches/ssl1.1.patch
  srcpkgs/virtuoso/patches/ssl1.1_more.patch
  srcpkgs/virtuoso/patches/use-mkstemp.patch
  srcpkgs/virtuoso/template
Labels: needs-testing

#42315 New package: git-delete-merged-branches-7.4.0
  srcpkgs/git-delete-merged-branches/template
Labels: new-package, Stale

#28895 common/build-style: check if go_import_path matches go.mod.
  common/build-style/go.sh
Labels: Stale

#44422 srcpkgs/*: remove all cryptocurrency/blockchain packages
  CONTRIBUTING.md
  common/shlibs
  srcpkgs/Electron-Cash/template
  srcpkgs/bitcoin-devel
  srcpkgs/bitcoin-qt
  srcpkgs/bitcoin/patches/fix-test.patch
  srcpkgs/bitcoin/template
  srcpkgs/bitcoin/update
  srcpkgs/cointop/template
  srcpkgs/cpuminer/template
  srcpkgs/electrum-ltc/patches/no-certifi.patch
  srcpkgs/electrum-ltc/template
  srcpkgs/electrum/files/README.voidlinux
  srcpkgs/electrum/template
  srcpkgs/electrum/update
  srcpkgs/geth
  srcpkgs/go-ethereum/template
  srcpkgs/libbitcoin-secp256k1-devel
  srcpkgs/libbitcoin-secp256k1/template
  srcpkgs/litecoin/patches/fix-include.patch
  srcpkgs/litecoin/template
  srcpkgs/monero-devel
  srcpkgs/monero-gui/INSTALL.msg
  srcpkgs/monero-gui/files
  srcpkgs/monero-gui/template
  srcpkgs/monero-gui/update
  srcpkgs/monero/files/monerod/run
  srcpkgs/monero/patches/easylogging.patch
  srcpkgs/monero/patches/fix-include.patch
  srcpkgs/monero/patches/march_cross.patch
  srcpkgs/monero/patches/system-miniupnpc.patch
  srcpkgs/monero/template
  srcpkgs/monero/update
  srcpkgs/namecoin/patches/boost-1.80.patch
  srcpkgs/namecoin/patches/fix-include.patch
  srcpkgs/namecoin/template
  srcpkgs/namecoin/update
  srcpkgs/nxt/files/bin/nxt
  srcpkgs/nxt/files/bin/nxt-tor
  srcpkgs/nxt/files/nxt-tor/run
  srcpkgs/nxt/files/nxt/run
  srcpkgs/nxt/template
  srcpkgs/removed-packages/template
  srcpkgs/swarm/template
Labels: remove

#42721 New package: graphwar-1.0.0
  srcpkgs/graphwar/files/graphwar
  srcpkgs/graphwar/files/graphwar-globalServer
  srcpkgs/graphwar/files/graphwar-roomServer
  srcpkgs/graphwar/template
Labels: new-package

#43260 New package: trurl-0.8
  srcpkgs/trurl/template
Labels: new-package

#42816 New package: rogue-5.4.4
  srcpkgs/rogue/patches/desktop-icon.patch
  srcpkgs/rogue/template
Labels: new-package

#43870 New package: autorestic-1.7.7
  srcpkgs/autorestic/template
Labels: new-package

#43618 New package: isoimagewriter-1.0.0
  srcpkgs/isoimagewriter/template
Labels: new-package

#43203 New package: fend-1.2.0
  srcpkgs/fend/template
Labels: new-package

#35034 New package: hydrus-525a
  srcpkgs/hydrus/template
Labels: new-package

#44546 New package: havoc-0.5.0
  srcpkgs/havoc/template
Labels: new-package
