Repository void-linux/void-packages, pull requests merged in 2023-10, with the labels that each got.

#46448 New package: pdfcpu-0.5.0
  srcpkgs/pdfcpu/template
Labels: new-package

#46510 wmii: remove
  srcpkgs/removed-packages/template
  srcpkgs/wmii/template
Labels: remove

#46511 tilp2: remove
  srcpkgs/removed-packages/template
  srcpkgs/tilp2/patches/no-kde.patch
  srcpkgs/tilp2/template
Labels: remove

#46532 New package: tecla-45.0
  srcpkgs/tecla/template
Labels: new-package

#46614 common/hooks/post-install/80-prepare-32bit.sh: use dot to reference directory content instead of wildcard
  common/hooks/post-install/80-prepare-32bit.sh
Labels: xbps-src

#46257 New package: fx-30.1.1
  srcpkgs/fx/template
Labels: new-package

#46677 New package: cmakelang-0.6.13
  srcpkgs/cmakelang/template
Labels: new-package

#46340 New package: ymir-0.0.5
  srcpkgs/ymir/template
Labels: new-package

#46760 New package: python3-dbus-next-0.2.3
  srcpkgs/python3-dbus-next/template
Labels: new-package

#46176 New package: numbat-1.6.3
  srcpkgs/numbat/template
Labels: new-package

#44139 New package: ast-grep-0.11.1
  srcpkgs/ast-grep/template
Labels: new-package

#44403 New package: gomuks-0.3.0
  srcpkgs/gomuks/template
Labels: new-package

#45723 New package: rofimoji-6.2.0
  srcpkgs/rofimoji/template
Labels: new-package

#46978 lighttpd: update to 1.4.73
  srcpkgs/lighttpd/template
Labels: needs-testing
