Repository void-linux/void-packages, pull requests merged in 2023-03, with the labels that each got.

#42585 New package: cargo-flamegraph-0.6.2
  srcpkgs/cargo-flamegraph/template
Labels: new-package

#42448 common: use HTTPS where working.
  common/environment/setup/misc.sh
  common/xbps-src/shutils/update_check.sh
Labels: xbps-src

#42573 common/hooks/do-extract/00-distfiles.sh: support .tar.zst
  common/hooks/do-extract/00-distfiles.sh
Labels: xbps-src

#41131 linux-firmware: update to 20230210
  srcpkgs/linux-firmware/template
Labels: core

#38897 New package: rpi-usbboot-20221104.153421
  srcpkgs/rpi-usbboot/patches/0001-Use-PREFIX-and-DESTDIR-in-Makefile.patch
  srcpkgs/rpi-usbboot/template
Labels: new-package, Stale

#40881 New package: nvidia-vaapi-driver-0.0.9
  srcpkgs/nvidia-vaapi-driver/template
Labels: new-package

#42796 New package: codeberg-cli-0.3.1
  srcpkgs/codeberg-cli/template
Labels: new-package

#36761 kdeconnect: add breeze-icons & kpeoplevcard to depends
  srcpkgs/kdeconnect/template
Labels: Stale

#42921 New package: libdex-0.2.0
  common/shlibs
  srcpkgs/libdex-devel
  srcpkgs/libdex/patches/libucontext.patch
  srcpkgs/libdex/template
Labels: new-package

#42517 New package: passt-2023.03.09.7c7625d
  srcpkgs/passt/template
  srcpkgs/passt/update
Labels: new-package

#40221 perl-SVG: update to 2.87.
  srcpkgs/perl-SVG/template
Labels: needs-testing

#43025 New package: Tuba-0.1.0
  srcpkgs/Tuba/template
Labels: new-package

#42927 New package: xdemineur-2.1.1
  srcpkgs/xdemineur/files/xdemineur.desktop
  srcpkgs/xdemineur/template
Labels: new-package

#42804 New package: gum-0.10.0
  srcpkgs/gum/template
Labels: new-package

#42929 soju: update to 0.6.0.
  srcpkgs/soju/template
Labels: needs-testing

#43044 New package: makefile2graph-2021.11.06
  srcpkgs/makefile2graph/template
Labels: new-package

#40932 coreutils: update to 9.2
  srcpkgs/coreutils/patches/0001-ls-restore-8.31-behavior-on-removed-directories.patch
  srcpkgs/coreutils/patches/cksum.patch
  srcpkgs/coreutils/patches/copy.patch
  srcpkgs/coreutils/template
Labels: needs-testing, core
