Repository void-linux/void-packages, pull requests merged in 2023-02, with the labels that each got.

#41968 vanitygen: remove
  srcpkgs/removed-packages/template
  srcpkgs/vanitygen/patches/4b814a646873c8439d3b5ee3a2278e727575521f.patch
  srcpkgs/vanitygen/patches/5f163e6fff7da52c4aecbd898d9df2e60a56f134.patch
  srcpkgs/vanitygen/template
Labels: remove

#41401 New package: vlna-1.5
  srcpkgs/vlna/template
Labels: new-package

#42103 Dutchhunspell
  srcpkgs/hunspell-nl_NL/template
Labels: new-package

#41750 New package: chrono-date-3.0.1
  common/shlibs
  srcpkgs/chrono-date-devel
  srcpkgs/chrono-date/patches/538_output_date_pc_for_pkg_config.patch
  srcpkgs/chrono-date/patches/disable_buggy_libstdc++_tests.patch
  srcpkgs/chrono-date/patches/get_info.patch
  srcpkgs/chrono-date/patches/sys_info.patch
  srcpkgs/chrono-date/template
Labels: new-package

#41961 common: cleanup trailing whitespaces
  common/build-helper/gir.sh
  common/build-helper/rust.sh
  common/build-style/configure.sh
  common/build-style/gem.sh
  common/build-style/gemspec.sh
  common/build-style/gnu-configure.sh
  common/build-style/gnu-makefile.sh
  common/build-style/slashpackage.sh
  common/chroot-style/ethereal.sh
  common/environment/configure/autoconf_cache/aarch64-linux
  common/environment/configure/autoconf_cache/arm-common
  common/environment/configure/autoconf_cache/ix86-common
  common/travis/xlint.sh
  common/xbps-src/shutils/consistency_check.sh
Labels: xbps-src

#42155 domain_exporter: update to 0.1.24.
  srcpkgs/domain_exporter/template
Labels: needs-testing

#42138 New package: hunspell-sr_SR-20130715.
  srcpkgs/hunspell-sr_SR/template
Labels: new-package

#40382 python3-regex: update to 2022.10.31.
  srcpkgs/python3-regex/template
Labels: Stale

#42158 v2ray: update to 5.3.0.
  srcpkgs/v2ray/template
Labels: needs-testing

#41572 gap: update to 4.12.2
  srcpkgs/gap/template
Labels: needs-testing

#42245 cawbird: remove package
  srcpkgs/cawbird/template
  srcpkgs/removed-packages/template
Labels: remove

#41420 New package: limine-4.20230215.0
  srcpkgs/limine-devel
  srcpkgs/limine/template
Labels: new-package

#41427 New package: ntfy-2.0.0
  srcpkgs/ntfy/files/ntfy-server/run
  srcpkgs/ntfy/patches/config.patch
  srcpkgs/ntfy/patches/no_short_commit.patch
  srcpkgs/ntfy/template
Labels: new-package

#41621 New package: Clipboard-0.3.2
  srcpkgs/Clipboard/template
Labels: new-package

#39405 New package: dooble-2023.01.30
  srcpkgs/dooble/patches/translations-dooble_application.patch
  srcpkgs/dooble/patches/translations-dooble_settings.patch
  srcpkgs/dooble/template
Labels: new-package

#42383 New package: obs-plugin-browser-bin-29.0.2
  srcpkgs/obs-plugin-browser-bin/template
Labels: new-package

#42406 New package: droidcam-obs-plugin-2.0.1.
  srcpkgs/droidcam-obs-plugin/template
Labels: new-package

#42224 [REDO] New package: qt6-webengine-6.4.2.
  common/shlibs
  srcpkgs/qt6-webengine-devel
  srcpkgs/qt6-webengine-examples
  srcpkgs/qt6-webengine/patches/0001-None-no-debug.patch
  srcpkgs/qt6-webengine/patches/0003-cross-hack.patch
  srcpkgs/qt6-webengine/patches/0050-no-glibc-cmake-check.patch
  srcpkgs/qt6-webengine/patches/0100-chromium-revert-9d080c0.patch
  srcpkgs/qt6-webengine/patches/0101-chromium-102-fenced_frame_utils-include.patch
  srcpkgs/qt6-webengine/patches/0102-chromium-102-regex_pattern-array.patch
  srcpkgs/qt6-webengine/patches/0103-chromium-i686-vaapi-fpermissive.patch
  srcpkgs/qt6-webengine/patches/0104-chromium-libxml-unbundle.patch
  srcpkgs/qt6-webengine/patches/0105-chromium-revert-drop-of-system-java.patch
  srcpkgs/qt6-webengine/patches/0106-chromium-system-nodejs.patch
  srcpkgs/qt6-webengine/patches/0107-chromium-cross-build.patch
  srcpkgs/qt6-webengine/patches/0108-chromium-cursed^Uscoped_file.patch
  srcpkgs/qt6-webengine/patches/0109-chromium-aarch64-musl-memory-tagging.patch
  srcpkgs/qt6-webengine/patches/0110-chromium-fix-missing-TEMP_FAILURE_RETRY-macro.patch
  srcpkgs/qt6-webengine/patches/0111-chromium-cstdint.patch
  srcpkgs/qt6-webengine/patches/0112-chromium-unistd.h.patch
  srcpkgs/qt6-webengine/patches/0113-chromium-pthread-stacksize.patch
  srcpkgs/qt6-webengine/patches/0114-do-not-narrow-int.patch
  srcpkgs/qt6-webengine/patches/0115-chromium-no-canonicalize-file-name.patch
  srcpkgs/qt6-webengine/patches/0116-chromium-musl-get-thread-name.patch
  srcpkgs/qt6-webengine/patches/0117-chromium-musl-resolver.patch
  srcpkgs/qt6-webengine/patches/0119-chromium-musl-stack-utils.patch
  srcpkgs/qt6-webengine/patches/0120-chromium-libc-malloc.patch
  srcpkgs/qt6-webengine/patches/0121-chromium-musl-stat.patch
  srcpkgs/qt6-webengine/patches/0122-chromium-condition_var.patch
  srcpkgs/qt6-webengine/patches/0123-chromium-musl-no-execinfo.patch
  srcpkgs/qt6-webengine/patches/0123-chromium-musl-no-getcontext.patch
  srcpkgs/qt6-webengine/patches/0124-chromium-enable-i686.patch
  srcpkgs/qt6-webengine/patches/0125-chromium-remove-strip_binary.patch
  srcpkgs/qt6-webengine/patches/0126-chromium-no-cdefs.patch
  srcpkgs/qt6-webengine/patches/0128-chromium-sandbox-membarrier.patch
  srcpkgs/qt6-webengine/patches/0129-chromium-sandbox-shed_getparam.patch
  srcpkgs/qt6-webengine/patches/0150-chromium-unbundle-ffmpeg-av_stream_get_first_dts.patch
  srcpkgs/qt6-webengine/patches/0151-chromium-unbundled-cross-toolchain.patch
  srcpkgs/qt6-webengine/patches/0152-chromium-webrtc-size_t.patch
  srcpkgs/qt6-webengine/patches/0153-chromium-webrtc-size_t.patch
  srcpkgs/qt6-webengine/patches/0154-chromium-uit_t.patch
  srcpkgs/qt6-webengine/patches/0200-chromium-sndio.patch
  srcpkgs/qt6-webengine/patches/0300-chromium-musl-hacks.patch
  srcpkgs/qt6-webengine/patches/0301-chromium-musl-sandbox.patch
  srcpkgs/qt6-webengine/patches/0302-chromium-no-mallinfo.patch
  srcpkgs/qt6-webengine/patches/0700-armv7l-neon.patch
  srcpkgs/qt6-webengine/patches/0750-chromium-musl-cross-no-asm_ptrace_h.patch
  srcpkgs/qt6-webengine/patches/0751-chromium-musl-arm-user_vfp.patch
  srcpkgs/qt6-webengine/patches/0752-chromium-musl-arm-elf_auxv_t.patch
  srcpkgs/qt6-webengine/patches/0900-cross-build-examples.patch
  srcpkgs/qt6-webengine/template
  srcpkgs/qt6-webengine/update
Labels: new-package

#40606 libtool: fix include paths when cross compiling
  srcpkgs/libtool/template
Labels: core

#41600 linux4.9: remove, EOL
  srcpkgs/linux4.9-dbg
  srcpkgs/linux4.9-headers
  srcpkgs/linux4.9/files/arm64-dotconfig
  srcpkgs/linux4.9/files/i386-dotconfig
  srcpkgs/linux4.9/files/mv-debug
  srcpkgs/linux4.9/files/ppc-dotconfig
  srcpkgs/linux4.9/files/ppc64-dotconfig
  srcpkgs/linux4.9/files/x86_64-dotconfig
  srcpkgs/linux4.9/patches/i2c-bcm2835.patch
  srcpkgs/linux4.9/patches/musl.patch
  srcpkgs/linux4.9/template
Labels: remove

#40366 safeeyes: remove pip from build depends
  srcpkgs/safeeyes/template
Labels: Stale
