Repository void-linux/void-packages, pull requests merged in 2023-08, with the labels that each got.

#42848 New package: font-inter-3.19
  srcpkgs/font-inter/template
Labels: new-package, Stale

#44944 sudo: update to 1.9.14p3.
  srcpkgs/sudo/template
Labels: core

#45384 openbazaar: drop package
  srcpkgs/openbazaar/files/void_service.EXAMPLE
  srcpkgs/openbazaar/template
  srcpkgs/removed-packages/template
Labels: remove

#45449 pam: update to 1.5.3.
  srcpkgs/pam/patches/no-examples.patch
  srcpkgs/pam/template
Labels: core

#45305 coreutils 9.3
  srcpkgs/coreutils/patches/cksum.patch
  srcpkgs/coreutils/patches/copy.patch
  srcpkgs/coreutils/template
Labels: core

#45226 New package: chayang-0.1.0
  srcpkgs/chayang/template
Labels: new-package

#44997 New package: sandbar-0.1
  srcpkgs/sandbar/template
Labels: new-package

#45295 New package: halloy-2023.4
  srcpkgs/halloy/template
Labels: new-package

#44882 New package: cookiecutter-2.3.0
  srcpkgs/cookiecutter/template
Labels: new-package

#45438 New package: wiki-tui-0.8.2
  srcpkgs/wiki-tui/template
Labels: new-package

#45557 xbps: patch in workaround for openssl3 compat
  srcpkgs/xbps/patches/openssl3.patch
  srcpkgs/xbps/patches/sig2.patch
  srcpkgs/xbps/template
Labels: core

#45593 New package: gdcalc-3.4
  srcpkgs/gdcalc/template
Labels: new-package

#45584 ecryptfs-utils: remove -python subpackage
  srcpkgs/ecryptfs-utils-python
  srcpkgs/ecryptfs-utils/template
  srcpkgs/removed-packages/template
Labels: remove

#45827 tekaim: remove package
  srcpkgs/removed-packages/template
  srcpkgs/tekaim/template
Labels: remove
