Repository void-linux/void-packages, pull requests merged in 2023-12, with the labels that each got.

#46951 New package: mlton-20210117
  srcpkgs/mlton/patches/20-polyml.patch
  srcpkgs/mlton/patches/30-mlbdeps.patch
  srcpkgs/mlton/patches/40-mlton.patch
  srcpkgs/mlton/patches/50-mlton-stubs.patch
  srcpkgs/mlton/patches/60-clean-polyml.patch
  srcpkgs/mlton/template
Labels: new-package

#47371 New package: dk-1.9
  srcpkgs/dk/template
Labels: new-package

#47164 New package: python3-pulsectl-asyncio-1.1.1
  srcpkgs/python3-pulsectl-asyncio/template
Labels: new-package

#47143 New package: flmsg-4.0.23
  srcpkgs/flmsg/template
Labels: new-package

#45949 e2fsprogs: use awk with compile_et
  srcpkgs/e2fsprogs/template
Labels: Stale

#36401 New package: jitterentropy-rngd-1.2.8
  srcpkgs/jitterentropy-rngd/template
  srcpkgs/jitterentropy-rngd/update
Labels: new-package, Stale

#47752 ulozto-downloader: remove package
  srcpkgs/removed-packages/template
  srcpkgs/ulozto-downloader/template
Labels: remove

#47799 new package: smlfmt-1.1
  srcpkgs/smlfmt/patches/destdir.patch
  srcpkgs/smlfmt/template
Labels: new-package

#47844 New package: wstunnel-8.4.1
  srcpkgs/wstunnel/template
Labels: new-package

#47615 New package: chess-tui-1.1.0
  srcpkgs/chess-tui/template
Labels: new-package

#47882 jdk21
  srcpkgs/openjdk21-doc
  srcpkgs/openjdk21-jmods
  srcpkgs/openjdk21-jre
  srcpkgs/openjdk21-src
  srcpkgs/openjdk21-static-libs
  srcpkgs/openjdk21/template
  srcpkgs/openjdk21/update
Labels: new-package

#40659 base-files: don't include lib32 files for musl
  srcpkgs/base-files/template
Labels: core

#47532 New package: sqsh-tools-1.3.0
  common/shlibs
  srcpkgs/libsqsh
  srcpkgs/libsqsh-devel
  srcpkgs/sqsh-tools/template
Labels: new-package

#47974 xbps-src: fix NOCOLORS
  common/environment/setup/sourcepkg.sh
Labels: xbps-src
