Repository void-linux/void-packages, pull requests merged in 2023-05, with the labels that each got.

#43476 zfs: update to 2.1.11.
  srcpkgs/zfs/template
Labels: core

#40246 wee-slack: update to 2.9.1
  srcpkgs/wee-slack/template
Labels: Stale

#43686 common/environment/setup/install.sh: support encoding in vman
  common/environment/setup/install.sh
Labels: xbps-src

#41909 lsof: update to 4.98.0
  srcpkgs/lsof/files/fix-github-ci.patch
  srcpkgs/lsof/patches/fix-epoll-test.patch
  srcpkgs/lsof/template
Labels: Stale

#42818 New package: bash-language-server-4.9.1
  srcpkgs/bash-language-server/template
Labels: new-package

#43229 New package: czkawka-5.1.0
  srcpkgs/czkawka/template
Labels: new-package

#43159 New package: ncdu2-2.2.2
  srcpkgs/ncdu2/patches/build-pie.patch
  srcpkgs/ncdu2/patches/explicit-cast.patch
  srcpkgs/ncdu2/template
Labels: new-package

#41825 leiningen: update to 2.10.0.
  srcpkgs/leiningen/template
Labels: Stale

#43331 New package: pmw-5.20
  srcpkgs/pmw/template
Labels: new-package

#42421 libnpupnp: update to 5.0.2
  srcpkgs/libnpupnp/template
Labels: Stale

#43289 xfsprogs: update to 6.3.0.
  srcpkgs/xfsprogs/template
Labels: core

#40468 bzip2-devel: add pkgconfig file
  srcpkgs/bzip2/files/bzip2.pc
  srcpkgs/bzip2/template
Labels: Stale

#43246 New package: shotman-0.4.3
  srcpkgs/shotman/template
Labels: new-package
