Repository void-linux/void-packages, pull requests merged in 2023-01, with the labels that each got.

#41365 usbutils: update to 015.
  srcpkgs/usbutils/template
Labels: core

#41127 sed: update to 4.9.
  srcpkgs/sed/template
Labels: core

#41353 New package: ulozto-downloader-3.3.0
  srcpkgs/ulozto-downloader/template
Labels: new-package

#41414 New package: python3-ipyparallel-8.4.1
  srcpkgs/python3-ipyparallel/patches/no-jupyterlab.patch
  srcpkgs/python3-ipyparallel/template
Labels: new-package

#41527 6cord: remove package
  srcpkgs/6cord/template
  srcpkgs/removed-packages/template
Labels: remove

#41509 btrfs-progs: update to 6.1.2.
  srcpkgs/btrfs-progs/template
Labels: core

#41262 New package: tqsl-2.6.5
  srcpkgs/tqsl/patches/icon.patch
  srcpkgs/tqsl/template
Labels: new-package

#41564 New package: gcalcli-4.3.0
  srcpkgs/gcalcli/template
Labels: new-package

#41488 New package: cliphist-0.3.1
  srcpkgs/cliphist/template
Labels: new-package

#41529 beignet: remove package
  srcpkgs/beignet/patches/cl_uint.patch
  srcpkgs/beignet/patches/e1b2419a0008e38ef2d9d255d9e9c74e9fba084b.patch
  srcpkgs/beignet/patches/llvm06.patch
  srcpkgs/beignet/patches/llvm08.patch
  srcpkgs/beignet/patches/llvm09.patch
  srcpkgs/beignet/patches/llvm10.patch
  srcpkgs/beignet/patches/llvm11.patch
  srcpkgs/beignet/patches/llvm12.patch
  srcpkgs/beignet/patches/musl.patch
  srcpkgs/beignet/template
  srcpkgs/beignet/update
  srcpkgs/removed-packages/template
Labels: remove

#41609 discord: update to 0.0.23.
  srcpkgs/discord/template
Labels: electron 🤮

#40760 New package: tofi-0.8.1
  srcpkgs/tofi/template
Labels: new-package

#33600 New package: ncspot-0.11.2
  srcpkgs/ncspot/template
Labels: new-package

#41400 steam-fonts: remove package
  srcpkgs/removed-packages/template
  srcpkgs/steam-fonts/template
Labels: remove

#41603 New package: logisim-evolution-3.8.0
  srcpkgs/logisim-evolution/files/logisim-evolution
  srcpkgs/logisim-evolution/patches/desktop-entry.patch
  srcpkgs/logisim-evolution/template
Labels: new-package

#41484 New package: ntdsextract2-0.9.1
  srcpkgs/ntdsextract2/template
Labels: new-package

#41018 transcode: remove package.
  srcpkgs/removed-packages/template
  srcpkgs/transcode/patches/musl.patch
  srcpkgs/transcode/patches/transcode-configure_in.patch
  srcpkgs/transcode/patches/transcode-ffmpeg3.patch
  srcpkgs/transcode/patches/transcode-ffmpeg4.patch
  srcpkgs/transcode/template
Labels: remove

#41766 csync: remove package
  srcpkgs/csync-devel
  srcpkgs/csync/template
  srcpkgs/csync/update
  srcpkgs/removed-packages/template
Labels: remove

#40118 afterstep: remove package
  srcpkgs/afterstep-devel
  srcpkgs/afterstep/patches/39-Fix-parallel-builds.patch
  srcpkgs/afterstep/patches/40-Fix-few-gcc-warnings.patch
  srcpkgs/afterstep/patches/43-Fix-gcc-warning.patch
  srcpkgs/afterstep/patches/44-Fix-build-with-gcc-5.patch
  srcpkgs/afterstep/patches/45-Fix-libAfterBase-Makefile.patch
  srcpkgs/afterstep/patches/50-cross-safe-min-max.patch
  srcpkgs/afterstep/patches/51-configure-pass-cross-alias-down.patch
  srcpkgs/afterstep/patches/52-libafterimage-cross.patch
  srcpkgs/afterstep/patches/fix-binutils-2.36+.patch
  srcpkgs/afterstep/template
  srcpkgs/removed-packages/template
Labels: remove, Stale

#41716 dracut: update to 059
  srcpkgs/dracut/patches/force_poweroff.patch
  srcpkgs/dracut/patches/kmod-fix.patch
  srcpkgs/dracut/patches/musl-__wordsize.patch
  srcpkgs/dracut/patches/network.patch
  srcpkgs/dracut/template
Labels: needs-testing, core

#40090 bfs: update to 2.6.2.
  srcpkgs/bfs/template
Labels: Stale

#40595 New package: jd-1.6.1
  srcpkgs/jd/template
Labels: new-package

#40201 New package: gitoxide-0.20.0
  srcpkgs/gitoxide/template
  srcpkgs/gitoxide/update
Labels: new-package

#41061 New package: boinctui-2.7.0
  srcpkgs/boinctui/patches/uint.patch
  srcpkgs/boinctui/template
Labels: new-package

#41390 New package: osv-scanner-1.0.2
  srcpkgs/osv-scanner/template
Labels: new-package

#41285 gopass: update to 1.15.2
  srcpkgs/gopass/template
Labels: needs-testing

#41599 xz: update to 5.4.1.
  srcpkgs/xz/template
Labels: core

#41858 rundird: remove package
  srcpkgs/removed-packages/template
  srcpkgs/rundird/files/rundird/run
  srcpkgs/rundird/template
Labels: remove

#41839 dkms: update to 3.0.10.
  srcpkgs/dkms/template
Labels: needs-testing, core
