Repository void-linux/void-packages, pull requests merged in 2024-03, with the labels that each got.

#48764 New package: snapshot-45.2
  srcpkgs/snapshot/template
Labels: new-package

#49097 New package: mqttcli-0.2.0.
  srcpkgs/mqttcli/template
Labels: new-package

#49234 New package: linux6.8-6.8.0
  srcpkgs/linux6.8-dbg
  srcpkgs/linux6.8-headers
  srcpkgs/linux6.8/files/arm64-dotconfig
  srcpkgs/linux6.8/files/i386-dotconfig
  srcpkgs/linux6.8/files/mv-debug
  srcpkgs/linux6.8/files/x86_64-dotconfig
  srcpkgs/linux6.8/patches/fix-musl-objtool.patch
  srcpkgs/linux6.8/patches/fixdep-largefile.patch
  srcpkgs/linux6.8/template
Labels: new-package

#46476 lynis: update to 3.0.9.
  srcpkgs/lynis/template
Labels: Stale

#48763 New package: uv-0.1.21
  srcpkgs/uv/template
Labels: new-package

#49334 New package: python3-paho_mqtt-2.0.0
  srcpkgs/python3-paho_mqtt/template
Labels: new-package

#49391 xbps-src: allow curl to request compressed responses in update-check
  common/xbps-src/shutils/update_check.sh
Labels: xbps-src

#48502 New-package: ironbar-0.14.1
  srcpkgs/ironbar/template
Labels: new-package
