Repository void-linux/void-packages, pull requests merged in 2024-12, with the labels that each got.

#52794 new package: niri 0.1.10.1
  srcpkgs/niri/patches/remove-session.patch
  srcpkgs/niri/template
Labels: new-package

#50494 New package: jaq-2.0.0
  srcpkgs/jaq/template
Labels: new-package

#53419 linux6.10: remove package.
  srcpkgs/linux6.10/files/arm64-dotconfig
  srcpkgs/linux6.10/files/i386-dotconfig
  srcpkgs/linux6.10/files/mv-debug
  srcpkgs/linux6.10/files/x86_64-dotconfig
  srcpkgs/linux6.10/patches/fix-musl-btf-ids.patch
  srcpkgs/linux6.10/patches/fix-musl-objtool.patch
  srcpkgs/linux6.10/patches/fixdep-largefile.patch
  srcpkgs/linux6.10/patches/soc-qcom-add-in-kernel-pd-mapper-implementation.patch
  srcpkgs/linux6.10/template
Labels: remove

#53418 linux4.19: remove package.
  srcpkgs/linux4.19/files/DocBook/Makefile
  srcpkgs/linux4.19/files/arm-dotconfig
  srcpkgs/linux4.19/files/arm64-dotconfig
  srcpkgs/linux4.19/files/i386-dotconfig
  srcpkgs/linux4.19/files/mv-debug
  srcpkgs/linux4.19/files/ppc-dotconfig
  srcpkgs/linux4.19/files/ppc64-dotconfig
  srcpkgs/linux4.19/files/ppc64le-dotconfig
  srcpkgs/linux4.19/files/x86_64-dotconfig
  srcpkgs/linux4.19/patches/ppc64-be-elfv2.patch
  srcpkgs/linux4.19/patches/ppcle-broken-vdso.patch
  srcpkgs/linux4.19/patches/ppcle-enable.patch
  srcpkgs/linux4.19/patches/ppcle-ll-compat-sys.patch
  srcpkgs/linux4.19/template
Labels: remove

#53401 common: move handling of rdeps, shlib-provides, shlib-requires files
  common/hooks/do-pkg/00-gen-pkg.sh
  common/hooks/post-install/06-strip-and-debug-pkgs.sh
  common/hooks/post-install/98-shlib-provides.sh
  common/hooks/pre-pkg/04-generate-runtime-deps.sh
  common/hooks/pre-pkg/05-generate-32bit-runtime-deps.sh
  common/hooks/pre-pkg/99-pkglint.sh
  common/hooks/pre-pkg/999-collected-rdeps.sh
  common/xbps-src/shutils/show.sh
Labels: xbps-src

#53420 linux6.11: remove package.
  srcpkgs/linux6.11/files/arm64-dotconfig
  srcpkgs/linux6.11/files/i386-dotconfig
  srcpkgs/linux6.11/files/mv-debug
  srcpkgs/linux6.11/files/x86_64-dotconfig
  srcpkgs/linux6.11/patches/fix-musl-btf-ids.patch
  srcpkgs/linux6.11/patches/fix-musl-objtool.patch
  srcpkgs/linux6.11/patches/fixdep-largefile.patch
  srcpkgs/linux6.11/patches/x13s-camera.patch
  srcpkgs/linux6.11/template
Labels: remove

#53585 lvm2: update to 2.03.29.
  srcpkgs/lvm2/patches/fix-stdio-usage.patch
  srcpkgs/lvm2/template
Labels: core

#53626 linux: update to 6.12.
  srcpkgs/linux/template
Labels: core

#52519 New package: firewalld-2.2.1
  srcpkgs/firewalld-applet
  srcpkgs/firewalld-config
  srcpkgs/firewalld/files/firewalld/check
  srcpkgs/firewalld/files/firewalld/conf
  srcpkgs/firewalld/files/firewalld/run
  srcpkgs/firewalld/template
Labels: new-package
