Repository void-linux/void-packages, pull requests merged in 2024-02, with the labels that each got.

#42667 New package: systemd-boot-efistub-255.3
  srcpkgs/systemd-boot-efistub/patches/musl-wchar_t.patch
  srcpkgs/systemd-boot-efistub/template
  srcpkgs/ukify
Labels: new-package

#48506 environment/configure/hardening.sh: fix copy-paste error with nopie=yes
  common/environment/configure/hardening.sh
Labels: xbps-src

#48160 New package: gazou-0.3.3
  srcpkgs/gazou/template
Labels: new-package

#46928 New package: bluetuith-0.1.8
  srcpkgs/bluetuith/template
Labels: new-package

#47075 guake: update to 3.10.
  srcpkgs/guake/template
Labels: Stale

#48710 New package: OpenCL-CLHPP-2023.12.14
  srcpkgs/OpenCL-CLHPP/template
Labels: new-package

#48285 New package: pcsc-cyberjack-3.99.5
  srcpkgs/pcsc-cyberjack/template
Labels: new-package

#47083 rust-bindgen: update to 0.69.4.
  srcpkgs/rust-bindgen/template
Labels: Stale

#48833 xbps-src: don't mess with masterdir set in argv
  xbps-src
Labels: xbps-src

#48545 New package: ibus-chewing
  srcpkgs/ibus-chewing/template
Labels: new-package
