Repository void-linux/void-packages, pull requests merged in 2024-05, with the labels that each got.

#49301 New package: sequoia-chameleon-gnupg-0.7.0
  srcpkgs/sequoia-chameleon-gnupg/template
Labels: new-package

#50229 common/build-helper/meson.sh: Fix deprecation warn
  common/build-helper/meson.sh
Labels: xbps-src

#48810 common/chroot-style/uchroot.sh: check if xbps-uchroot is executable
  common/chroot-style/uchroot.sh
Labels: xbps-src

#48686 swaykbdd: update to 1.4.
  srcpkgs/swaykbdd/template
Labels: Stale

#48025 lego: update to 4.15.0.
  srcpkgs/lego/template
Labels: Stale

#50313 New package: linux6.9-6.9.0
  srcpkgs/linux6.9-dbg
  srcpkgs/linux6.9-headers
  srcpkgs/linux6.9/files/arm64-dotconfig
  srcpkgs/linux6.9/files/i386-dotconfig
  srcpkgs/linux6.9/files/mv-debug
  srcpkgs/linux6.9/files/x86_64-dotconfig
  srcpkgs/linux6.9/patches/fix-musl-btf-ids.patch
  srcpkgs/linux6.9/patches/fix-musl-objtool.patch
  srcpkgs/linux6.9/patches/fixdep-largefile.patch
  srcpkgs/linux6.9/template
Labels: new-package

#48844 New package: eww-0.6.0
  srcpkgs/eww/template
Labels: new-package

#50414 vscl: remove package
  srcpkgs/vscl/files/README.voidlinux
  srcpkgs/vscl/files/vscl
  srcpkgs/vscl/files/vscl-update
  srcpkgs/vscl/files/vscl.conf
  srcpkgs/vscl/template
Labels: remove

#50400 New package: zk-0.14.0
  srcpkgs/zk/template
Labels: new-package
