Repository void-linux/void-packages, pull requests merged in 2024-06, with the labels that each got.

#48828 glslViewer: update to 3.2.4.
  srcpkgs/glslViewer/patches/liblo.patch
  srcpkgs/glslViewer/template
Labels: Stale

#47880 backintime: update to 1.4.3.
  srcpkgs/backintime/patches/e1ae23ddc0b4229053e3e9c6c61adcb7f3d8e9b3.patch
  srcpkgs/backintime/template
Labels: Stale

#48676 common/environment/setup/install.sh: fix v* funcs for paths with spaces
  common/environment/setup/install.sh
Labels: xbps-src

#50757 apparmor: update to 3.1.7.
  srcpkgs/apparmor/patches/libapparmor-basename.patch
  srcpkgs/apparmor/template
Labels: core

#46909 New package: yazi-0.2.5
  srcpkgs/yazi/template
Labels: new-package

#49036 srcpkgs/: use ${version} in distfiles
  srcpkgs/codec2/template
  srcpkgs/dcadec/template
  srcpkgs/font-libre-hebrew/template
  srcpkgs/fsv/template
  srcpkgs/gnunet/template
  srcpkgs/gsoap/template
  srcpkgs/iotop/template
  srcpkgs/lbzip2/template
  srcpkgs/libx86/template
  srcpkgs/par/template
  srcpkgs/pingus/template
  srcpkgs/python3-pychm/template
  srcpkgs/qt5-webkit/template
  srcpkgs/taglib-extras/template
Labels: Stale

#49034 tuir: adjust for python 3.12 method removal
  srcpkgs/tuir/patches/0001-Adjust-for-python-3.12-method-removal.patch
  srcpkgs/tuir/template
Labels: Stale

#49331 pam-mount: update to 2.20.
  srcpkgs/pam-mount/patches/add-luks2-support.patch
  srcpkgs/pam-mount/template
Labels: Stale

#49353 vpsm: remove package
  srcpkgs/removed-packages/template
  srcpkgs/vpsm/patches/setuid-fix.patch
  srcpkgs/vpsm/template
Labels: remove

#50855 New package: biboumi-9.0.
  srcpkgs/biboumi/files/biboumi/run
  srcpkgs/biboumi/patches/remove-git.patch
  srcpkgs/biboumi/template
Labels: new-package

#47552 New package: swww-0.9.5
  srcpkgs/swww/template
Labels: new-package

#50977 tootle: remove package
  srcpkgs/removed-packages/template
  srcpkgs/tootle/patches/vala-0.54.patch
  srcpkgs/tootle/patches/vala-0.56.patch
  srcpkgs/tootle/patches/vala-0.56b.patch
  srcpkgs/tootle/template
Labels: remove

#49367 New package: duckdb-1.0.0
  srcpkgs/duckdb-devel
  srcpkgs/duckdb/template
  srcpkgs/python3-duckdb
Labels: new-package
