Repository void-linux/void-packages, pull requests merged in 2024-01, with the labels that each got.

#47103 New package: postgrest-10.2.0
  srcpkgs/postgrest/template
Labels: new-package

#47413 New package: kmplot
  srcpkgs/kmplot/template
Labels: new-package

#47931 glibc: depend on libxcrypt to ensure partial upgrades work
  srcpkgs/glibc/template
Labels: core

#48033 New package: garage-0.9.0
  srcpkgs/garage/patches/build-on-macos.patch
  srcpkgs/garage/template
Labels: new-package

#45947 New package: gtkgreet-0.8
  srcpkgs/gtkgreet/template
Labels: new-package

#45739 New package: ntpd-rs-1.1.0
  srcpkgs/ntpd-rs/INSTALL
  srcpkgs/ntpd-rs/files/ntpd-rs/run
  srcpkgs/ntpd-rs/template
Labels: new-package

#47570 new package: dinit
  srcpkgs/dinit/template
Labels: new-package

#48149 libnl: drop package
  srcpkgs/libnl-devel
  srcpkgs/libnl/patches/fix-includes.patch
  srcpkgs/libnl/patches/fix-strerror_r.patch
  srcpkgs/libnl/patches/libnl-1.1-flags.patch
  srcpkgs/libnl/template
  srcpkgs/libnl/update
Labels: remove

#48137 New package: linux6.7-6.7.0
  srcpkgs/linux6.7-dbg
  srcpkgs/linux6.7-headers
  srcpkgs/linux6.7/files/arm64-dotconfig
  srcpkgs/linux6.7/files/i386-dotconfig
  srcpkgs/linux6.7/files/mv-debug
  srcpkgs/linux6.7/files/x86_64-dotconfig
  srcpkgs/linux6.7/patches/fix-musl-objtool.patch
  srcpkgs/linux6.7/patches/fixdep-largefile.patch
  srcpkgs/linux6.7/template
Labels: new-package

#44235 New package: brother-brscan5-1.2.13
  srcpkgs/brother-brscan5/INSTALL
  srcpkgs/brother-brscan5/REMOVE
  srcpkgs/brother-brscan5/files/README.voidlinux
  srcpkgs/brother-brscan5/template
Labels: new-package

#44972 New package: DSView-1.3.0
  srcpkgs/DSView/template
Labels: new-package, Stale

#48270 setup/archive: fix extraction of non-tar gz/bz2/xz/zst archives
  common/environment/setup/archive.sh
Labels: xbps-src

#46861 New package: perl-IO-Compress-Brotli-0.004001
  srcpkgs/perl-IO-Compress-Brotli/patches/no-bundled-brotli.patch
  srcpkgs/perl-IO-Compress-Brotli/template
Labels: new-package, Stale

#48326 linux6.5: remove (EOL)
  srcpkgs/linux6.5-dbg
  srcpkgs/linux6.5-headers
  srcpkgs/linux6.5/files/arm64-dotconfig
  srcpkgs/linux6.5/files/i386-dotconfig
  srcpkgs/linux6.5/files/mv-debug
  srcpkgs/linux6.5/files/x86_64-dotconfig
  srcpkgs/linux6.5/patches/fix-musl-objtool.patch
  srcpkgs/linux6.5/patches/fixdep-largefile.patch
  srcpkgs/linux6.5/template
Labels: remove
