Repository void-linux/void-packages, pull requests merged in 2024-04, with the labels that each got.

#46973 New package: q-0.19.2
  srcpkgs/q/template
Labels: new-package

#49668 New package: cargo-watch-8.5.2
  srcpkgs/cargo-watch/template
Labels: new-package

#49795 openssl: update to 3.3.0.
  srcpkgs/openssl-doc
  srcpkgs/openssl/template
Labels: core

#49794 [RFC] New package: libssl1.1-1.1.1w
  srcpkgs/libcrypto1.1
  srcpkgs/libssl1.1/template
Labels: new-package

#48947 rest0: remove package
  common/shlibs
  srcpkgs/removed-packages/template
  srcpkgs/rest0-devel
  srcpkgs/rest0/template
Labels: remove

#48893 midori: remove package
  srcpkgs/midori/template
  srcpkgs/removed-packages/template
Labels: remove

#48817 grub: update to 2.12.
  srcpkgs/grub/patches/revert-fwsetup-2.12.patch
  srcpkgs/grub/patches/xfs.patch
  srcpkgs/grub/patches/xx-e2fsprogs-1.patch
  srcpkgs/grub/patches/xx-e2fsprogs-2.patch
  srcpkgs/grub/template
Labels: core
