Repository void-linux/void-packages, pull requests merged in 2024-09, with the labels that each got.

#52028 linux6.9: remove, EOL
  srcpkgs/linux6.9/files/arm64-dotconfig
  srcpkgs/linux6.9/files/i386-dotconfig
  srcpkgs/linux6.9/files/mv-debug
  srcpkgs/linux6.9/files/x86_64-dotconfig
  srcpkgs/linux6.9/patches/fix-musl-btf-ids.patch
  srcpkgs/linux6.9/patches/fix-musl-objtool.patch
  srcpkgs/linux6.9/patches/fixdep-largefile.patch
  srcpkgs/linux6.9/patches/soc-qcom-add-in-kernel-pd-mapper-implementation.patch
  srcpkgs/linux6.9/template
Labels: remove

#52247 common/build-style/go.sh: support $make_check_pre
  common/build-style/go.sh
Labels: xbps-src

#52215 common/build-style/cargo.sh: add make_build_args to build
  common/build-style/cargo.sh
Labels: xbps-src

#52249 New package: linux6.11-6.11.0
  srcpkgs/linux6.11-dbg
  srcpkgs/linux6.11-headers
  srcpkgs/linux6.11/files/arm64-dotconfig
  srcpkgs/linux6.11/files/i386-dotconfig
  srcpkgs/linux6.11/files/mv-debug
  srcpkgs/linux6.11/files/x86_64-dotconfig
  srcpkgs/linux6.11/patches/fix-musl-btf-ids.patch
  srcpkgs/linux6.11/patches/fix-musl-objtool.patch
  srcpkgs/linux6.11/patches/fixdep-largefile.patch
  srcpkgs/linux6.11/template
Labels: new-package

#52277 hardinfo: remove package
  srcpkgs/hardinfo/patches/fix-runtime.patch
  srcpkgs/hardinfo/template
  srcpkgs/hardinfo/update
  srcpkgs/removed-packages/template
Labels: remove

#51521 New package: mepo-1.3.3.
  srcpkgs/mepo/template
Labels: new-package

#50819 [RFC] Manual.md: use SPDX expressions for license=
  Manual.md
Labels: xbps-src

#52367 New package: libsfdo-0.1.3
  common/shlibs
  srcpkgs/libsfdo-devel
  srcpkgs/libsfdo/template
Labels: new-package
