Repository void-linux/void-packages, pull requests merged in 2024-11, with the labels that each got.

#48019 New package: matterbridge-1.26.0.
  srcpkgs/matterbridge/files/matterbridge/run
  srcpkgs/matterbridge/template
Labels: new-package, Stale

#52037 New package: libgpiod-2.1.3
  srcpkgs/libgpiod-devel
  srcpkgs/libgpiod-python3
  srcpkgs/libgpiod-tools
  srcpkgs/libgpiod/template
Labels: new-package

#51468 New package: odilia-0.1.4
  srcpkgs/odilia/patches/fix-lock.diff
  srcpkgs/odilia/template
Labels: new-package

#51961 New package: clj-kondo-2024.11.14
  srcpkgs/clj-kondo/template
Labels: new-package

#53029 sudo: update to 1.9.16.
  srcpkgs/sudo/patches/install_perms.patch
  srcpkgs/sudo/template
Labels: core

#53134 New package: linux6.12-6.12.0
  srcpkgs/linux6.12-dbg
  srcpkgs/linux6.12-headers
  srcpkgs/linux6.12/files/arm64-dotconfig
  srcpkgs/linux6.12/files/i386-dotconfig
  srcpkgs/linux6.12/files/mv-debug
  srcpkgs/linux6.12/files/x86_64-dotconfig
  srcpkgs/linux6.12/patches/fix-musl-btf-ids.patch
  srcpkgs/linux6.12/patches/fix-musl-objtool.patch
  srcpkgs/linux6.12/patches/fixdep-largefile.patch
  srcpkgs/linux6.12/patches/x13s-camera.patch
  srcpkgs/linux6.12/template
Labels: new-package

#52004 New package: valkey-8.0.1
  srcpkgs/valkey-redis
  srcpkgs/valkey/files/valkey-sentinel/run
  srcpkgs/valkey/files/valkey/run
  srcpkgs/valkey/patches/system-jemalloc.patch
  srcpkgs/valkey/template
Labels: new-package

#53138 gogs: remove package
  srcpkgs/gogs/INSTALL
  srcpkgs/gogs/files/gogs.ini
  srcpkgs/gogs/files/gogs/run
  srcpkgs/gogs/template
  srcpkgs/removed-packages/template
Labels: remove

#53158 New package: flnet-7.5.0
  srcpkgs/flnet/template
Labels: new-package

#53087 New package: fllog-1.2.8
  srcpkgs/fllog/template
Labels: new-package

#51484 New package: remote-touchpad
  srcpkgs/remote-touchpad/template
Labels: new-package
