Repository void-linux/void-packages, pull requests merged in 2024-07, with the labels that each got.

#51009 New package: xfce4-panel-profiles-1.0.14
  srcpkgs/xfce4-panel-profiles/template
Labels: new-package

#48658 New package: winegui-2.5.0
  srcpkgs/winegui/files/README.voidlinux
  srcpkgs/winegui/template
Labels: new-package

#50989 hooks/post-install: check for -private-devel if PRIVATE_API is used
  common/hooks/post-install/15-qt-private-api.sh
Labels: xbps-src

#50881 New package: yamlfmt-0.13.0
  srcpkgs/yamlfmt/template
Labels: new-package

#47862 New package: VVVVVV-2.3.6.
  srcpkgs/VVVVVV/patches/data-zip-path.diff
  srcpkgs/VVVVVV/template
Labels: new-package, Stale

#50907 gamehub: remove package
  srcpkgs/gamehub/template
  srcpkgs/removed-packages/template
Labels: remove

#51278 New package: linux6.10-6.10.0
  srcpkgs/linux6.10-dbg
  srcpkgs/linux6.10-headers
  srcpkgs/linux6.10/files/arm64-dotconfig
  srcpkgs/linux6.10/files/i386-dotconfig
  srcpkgs/linux6.10/files/mv-debug
  srcpkgs/linux6.10/files/x86_64-dotconfig
  srcpkgs/linux6.10/patches/fix-musl-btf-ids.patch
  srcpkgs/linux6.10/patches/fix-musl-objtool.patch
  srcpkgs/linux6.10/patches/fixdep-largefile.patch
  srcpkgs/linux6.10/patches/soc-qcom-add-in-kernel-pd-mapper-implementation.patch
  srcpkgs/linux6.10/template
Labels: new-package

#51323 New package: wlroots0.18-0.18.0
  common/shlibs
  srcpkgs/wlroots0.18-devel
  srcpkgs/wlroots0.18/template
  srcpkgs/wlroots0.18/update
Labels: new-package

#51380 New package: spex-x replaces spek-alternative for ffmpeg6
  srcpkgs/spek-alternative
  srcpkgs/spek-alternative/template
  srcpkgs/spek-x/patches/musl.patch
  srcpkgs/spek-x/template
Labels: new-package

#51364 New package: cloud-utils-0.33.
  srcpkgs/cloud-guest-utils/template
  srcpkgs/cloud-image-utils
  srcpkgs/cloud-utils
  srcpkgs/cloud-utils-ec2metadata
Labels: new-package

#44553 New package: clojure-lsp-2024.04.22
  srcpkgs/clojure-lsp/patches/remove-pgo.patch
  srcpkgs/clojure-lsp/template
  srcpkgs/clojure-lsp/update
Labels: new-package

#49215 New package: soft-serve-0.7.4
  srcpkgs/soft-serve/files/soft-serve/run
  srcpkgs/soft-serve/template
Labels: new-package

#51051 New package: treefmt-2.0.1
  srcpkgs/treefmt/template
Labels: new-package

#50777 New package: python3-pillow_heif-0.17.0
  srcpkgs/python3-pillow_heif/template
Labels: new-package

#45998 New package: stegseek-0.6
  srcpkgs/stegseek/patches/portable-types.patch
  srcpkgs/stegseek/template
Labels: new-package

#50961 New package: typstyle-0.11.28
  srcpkgs/typstyle/template
Labels: new-package

#49049 New package: swaysome-2.1.1.
  srcpkgs/swaysome/template
Labels: new-package

#45862 New package: efm-langserver-0.0.52
  srcpkgs/efm-langserver/template
Labels: new-package

#47980 New package: cpufetch-1.05
  srcpkgs/cpufetch/template
Labels: new-package

#44875 New package: UxPlay-1.68.3
  srcpkgs/UxPlay/files/README.voidlinux
  srcpkgs/UxPlay/template
Labels: new-package

#49892 New package: xq-1.2.4
  srcpkgs/xq/template
Labels: new-package

#48601 New package: opentofu-1.7.3
  srcpkgs/opentofu/template
Labels: new-package

#51186 remove llvm12
  common/shlibs
  srcpkgs/libllvm12
  srcpkgs/llvm12/files/llvm-Config-llvm-config.h
  srcpkgs/llvm12/patches/clang-001-fix-unwind-chain-inclusion.patch
  srcpkgs/llvm12/patches/clang-002-add-musl-triples.patch
  srcpkgs/llvm12/patches/clang-003-ppc64-dynamic-linker-path.patch
  srcpkgs/llvm12/patches/clang-004-ppc64-musl-elfv2.patch
  srcpkgs/llvm12/patches/compiler-rt-aarch64-ucontext.patch
  srcpkgs/llvm12/patches/compiler-rt-sanitizer-glibc-2.36.patch
  srcpkgs/llvm12/patches/compiler-rt-sanitizer-ppc64-musl.patch
  srcpkgs/llvm12/patches/compiler-rt-size_t.patch
  srcpkgs/llvm12/patches/compiler-rt-xray-ppc64-musl.patch
  srcpkgs/llvm12/patches/libcxx-musl.patch
  srcpkgs/llvm12/patches/libcxx-ppc.patch
  srcpkgs/llvm12/patches/libcxx-ssp-nonshared.patch
  srcpkgs/llvm12/patches/libcxxabi-dl.patch
  srcpkgs/llvm12/patches/libunwind-ppc32.patch
  srcpkgs/llvm12/patches/lldb-musl.patch
  srcpkgs/llvm12/patches/llvm-001-musl.patch
  srcpkgs/llvm12/patches/llvm-002-musl-ppc64-elfv2.patch
  srcpkgs/llvm12/patches/llvm-003-ppc-secureplt.patch
  srcpkgs/llvm12/patches/llvm-004-override-opt.patch
  srcpkgs/llvm12/patches/llvm-005-ppc-bigpic.patch
  srcpkgs/llvm12/patches/llvm-006-aarch64-mf_exec.patch
  srcpkgs/llvm12/patches/llvm-gcc13.patch
  srcpkgs/llvm12/patches/ppc32-compiler-rt.patch
  srcpkgs/llvm12/template
  srcpkgs/llvm12/update
  srcpkgs/removed-packages/template
Labels: remove
