Repository void-linux/void-packages, pull requests merged in 2025-07, with the labels that each got.

#55319 New package: wishlist-0.15.2
  srcpkgs/wishlist/template
Labels: new-package

#55696 protonvpn-cli: remove package
  srcpkgs/protonvpn-cli/template
  srcpkgs/removed-packages/template
Labels: remove

#50604 New package: asm-lsp-0.10.0
  srcpkgs/asm-lsp/template
Labels: new-package

#56223 New package: wthrr-1.2.1
  srcpkgs/wthrr/patches/fix-builds.patch
  srcpkgs/wthrr/template
Labels: new-package

#56240 new vibe package
  srcpkgs/vibe/template
Labels: new-package

#56130 seer: update to 2.5
  srcpkgs/seer/template
Labels: needs-testing

#56456 New package: irust-1.74.0
  srcpkgs/irust/files/README.voidlinux
  srcpkgs/irust/template
Labels: new-package

#56215 New package: pistol-0.5.2
  srcpkgs/pistol/template
Labels: new-package

#56142 New package: lidm-1.2.3
  srcpkgs/lidm/files/lidm/finish
  srcpkgs/lidm/files/lidm/run
  srcpkgs/lidm/template
Labels: new-package
