Repository void-linux/void-packages, pull requests merged in 2025-01, with the labels that each got.

#53769 New package: usbkvm-0.1.0
  srcpkgs/usbkvm/template
Labels: new-package

#52422 New package: discover-6.1.5
  srcpkgs/discover/template
Labels: new-package

#49996 add ttf-vista-fonts package (nonfree)
  srcpkgs/ttf-vista-fonts/template
Labels: new-package, Stale

#53438 New package: xwayland-satellite-0.5
  srcpkgs/xwayland-satellite/template
Labels: new-package

#52741 tiff: update to 4.7.0.
  srcpkgs/tiff/template
Labels: Stale
