Repository void-linux/void-packages, pull requests merged in 2025-02, with the labels that each got.

#51014 New package: golang-migrate-4.18.1
  srcpkgs/migrate/template
Labels: new-package, Stale

#54106 New package: SDL3-3.2.0
  srcpkgs/SDL3-devel
  srcpkgs/SDL3/template
Labels: new-package

#54206 xbps-src: re-run post-install hooks if -f flag is used
  common/xbps-src/libexec/xbps-src-doinstall.sh
Labels: xbps-src

#54273 mozjs102: remove package
  srcpkgs/mozjs102-devel
  srcpkgs/mozjs102/patches/001-fix-soname.patch
  srcpkgs/mozjs102/patches/002-copy-headers.patch
  srcpkgs/mozjs102/patches/003-tests-timeout.patch
  srcpkgs/mozjs102/patches/004-icu-sources-data-py-decouple.patch
  srcpkgs/mozjs102/patches/005-icu-sources-data-write-command-stderr.patch
  srcpkgs/mozjs102/patches/006-emitter.patch
  srcpkgs/mozjs102/patches/007-tests-use-native-temporarydirectory.patch
  srcpkgs/mozjs102/patches/008-init-patch.patch
  srcpkgs/mozjs102/patches/009-sloppy-m4-detection.patch
  srcpkgs/mozjs102/patches/011-failing-tests-ppc64-s390x.patch
  srcpkgs/mozjs102/patches/012-fix-musl.patch
  srcpkgs/mozjs102/patches/013-disable-spidermonkey-jslint.patch
  srcpkgs/mozjs102/patches/014-rust-target.patch
  srcpkgs/mozjs102/patches/015-drop-rustc-validation.patch
  srcpkgs/mozjs102/patches/017-no-lto-readelf.patch
  srcpkgs/mozjs102/patches/MOZ_NO_RUST_LTO.patch
  srcpkgs/mozjs102/patches/armv6l-isb.patch
  srcpkgs/mozjs102/patches/fix-build-ppc32.patch
  srcpkgs/mozjs102/patches/fix-i386-fdlibm.patch
  srcpkgs/mozjs102/patches/python3.12-looseversion.patch
  srcpkgs/mozjs102/template
  srcpkgs/mozjs102/update
  srcpkgs/removed-packages/template
Labels: remove

#52408 runit: update to 2.2.0.
  srcpkgs/runit/patches/chpst-pwd.patch
  srcpkgs/runit/patches/chpst.patch
  srcpkgs/runit/patches/clearmem.patch
  srcpkgs/runit/patches/cross.patch
  srcpkgs/runit/patches/default_svdir.patch
  srcpkgs/runit/patches/sigcont.patch
  srcpkgs/runit/patches/svlogd.patch
  srcpkgs/runit/patches/utmpset-time_t.patch
  srcpkgs/runit/template
Labels: needs-testing, core

#54311 runit-void: update to 20250212.
  srcpkgs/runit-void/INSTALL.msg
  srcpkgs/runit-void/patches/util-linux-2.40.patch
  srcpkgs/runit-void/template
Labels: core

#53170 celluloid: update to 0.27
  srcpkgs/celluloid/template
Labels: Stale

#50027 New package: LACT-0.7.0
  srcpkgs/LACT/files/lact/run
  srcpkgs/LACT/template
Labels: new-package
