Repository void-linux/void-packages, pull requests merged in 2025-06, with the labels that each got.

#55526 New package: tint-0.1.3
  srcpkgs/tint/template
Labels: new-package

#55273 New package: shikane-1.0.1
  srcpkgs/shikane/template
Labels: new-package

#55264 New package: cargo-machete-0.8.0
  srcpkgs/cargo-machete/template
Labels: new-package

#55432 New package: showtime-48.1
  srcpkgs/showtime/template
Labels: new-package

#55397 New package: kompose-1.36.0
  srcpkgs/kompose/template
Labels: new-package

#55199 New package: better-control-6.11.7
  srcpkgs/better-control/template
Labels: new-package

#55197 New package: caligula-0.4.8
  srcpkgs/caligula/template
Labels: new-package

#54991 New package: gearlever-3.2.2
  srcpkgs/gearlever/template
Labels: new-package

#54804 New package: choose-v1.3.6
  srcpkgs/choose/template
Labels: new-package

#54797 New package: gaupol-1.15
  srcpkgs/gaupol/template
Labels: new-package

#54591 New package: matcha-2.1.0
  srcpkgs/matcha/template
Labels: new-package

#53908 New package: xfce4-smartbookmark-plugin-0.5.3
  srcpkgs/xfce4-smartbookmark-plugin/template
Labels: new-package

#54587 New package: age-plugin-yubikey-0.5.0
  srcpkgs/age-plugin-yubikey/template
Labels: new-package

#54969 New package: xiphos-4.3.1
  srcpkgs/xiphos/patches/build-without-uuidgen.patch
  srcpkgs/xiphos/patches/https-by-default.patch
  srcpkgs/xiphos/template
Labels: new-package

#55433 New package: tailspin-5.4.2
  srcpkgs/tailspin/template
Labels: new-package

#53803 New package: bibiman-0.11.4
  srcpkgs/bibiman/template
Labels: new-package

#53771 New package: Apktool-2.10.0
  srcpkgs/Apktool/files/Apktool
  srcpkgs/Apktool/template
Labels: new-package

#54357 New package: dune3d-1.3.0
  srcpkgs/dune3d/template
Labels: new-package

#53240 New package: cliflux-1.4.4
  srcpkgs/cliflux/template
Labels: new-package

#53031 New package: kew-3.3.2
  srcpkgs/kew/template
Labels: new-package

#52564 New package: typos-1.29.9
  srcpkgs/typos/template
Labels: new-package

#52390 New package: python3-pylsp-mypy-0.6.9
  srcpkgs/python3-pylsp-mypy/template
Labels: new-package

#52342 New package: pika-backup-0.7.4
  srcpkgs/pika-backup/patches/remove-git-describe.patch
  srcpkgs/pika-backup/template
Labels: new-package

#52218 New package: oils-for-unix-0.28.0
  srcpkgs/oils-for-unix/template
Labels: new-package

#52907 New package: json2tsv-1.2
  srcpkgs/json2tsv/template
Labels: new-package

#52989 New package: bmaptool-3.9.0
  srcpkgs/bmaptool/template
Labels: new-package

#55315 New package: labwc-menu-generator-0.2.0
  srcpkgs/labwc-menu-generator/template
Labels: new-package

#55189 New package: rmpc-0.8.0
  srcpkgs/rmpc/template
Labels: new-package

#55149 New package: neovide-0.15.0
  srcpkgs/neovide/template
Labels: new-package

#53632 New package: supersonic-desktop-0.15.2
  srcpkgs/supersonic-desktop/patches/println-to-printf.patch
  srcpkgs/supersonic-desktop/template
Labels: new-package

#53918 sq: update to 0.48.5.
  srcpkgs/sq/template
Labels: Stale

#54516 New package: exult-1.12.0
  srcpkgs/exult/template
Labels: new-package

#55347 New package: nikto-2.5.0
  srcpkgs/nikto/template
Labels: new-package

#55296 New package: powerline-go-1.25
  srcpkgs/powerline-go/template
Labels: new-package

#55316 New package: wl-clip-persist-0.4.3
  srcpkgs/wl-clip-persist/template
Labels: new-package

#55061 New package: zwm-0.1.2
  srcpkgs/zwm/patches/fix-makefile.patch
  srcpkgs/zwm/patches/fix-musl.patch
  srcpkgs/zwm/template
Labels: new-package

#55225 New package: shadowsocks-rust-1.23.2
  srcpkgs/shadowsocks-rust/files/shadowsocks-rust-client/run
  srcpkgs/shadowsocks-rust/files/shadowsocks-rust-server/run
  srcpkgs/shadowsocks-rust/template
Labels: new-package

#54856 New package: sov-0.95
  srcpkgs/sov/template
Labels: new-package

#54964 New package: kwin-effects-forceblur-1.3.6
  common/shlibs
  srcpkgs/kwin-effects-forceblur/template
Labels: new-package

#54643 shfmt: update to 3.11.0
  srcpkgs/shfmt/template
Labels: Stale

#54695 New package: fooyin-0.8.1
  srcpkgs/fooyin/patches/fix-cmake-sndfile.patch
  srcpkgs/fooyin/template
Labels: new-package

#54526 minicom: update to 2.10.
  srcpkgs/minicom/template
Labels: Stale

#54485 dooble: update to 2025.02.28.
  srcpkgs/dooble/patches/translations-dooble_application.patch
  srcpkgs/dooble/template
Labels: Stale

#52894 xbps-src: improve update-check pattern for GitHub
  common/xbps-src/shutils/update_check.sh
Labels: xbps-src

#52874 cargo-modules: update to 0.24.2.
  srcpkgs/cargo-modules/template
Labels: Stale

#51905 New package: gnome-network-displays-0.96.0
  srcpkgs/gnome-network-displays/template
Labels: new-package

#51817 New package: sprec-0.1
  srcpkgs/sprec/template
Labels: new-package

#50965 New package: pet-1.0.1
  srcpkgs/pet/template
Labels: new-package

#50310 New package: netscanner-0.6.2
  srcpkgs/netscanner/template
Labels: new-package

#48878 New package: synapse-compress-state-0.1.4
  srcpkgs/synapse-compress-state/template
Labels: new-package

#51365 New package: rage-0.10.0
  srcpkgs/rage/template
Labels: new-package

#53263 New package: pizauth
  srcpkgs/pizauth/template
Labels: new-package

#54503 New package: freecol-1.2.0
  srcpkgs/freecol/template
Labels: new-package

#38898 New package: tarlz-0.27.1
  srcpkgs/tarlz/template
Labels: new-package, Stale

#55614 New package: python3-pydot-4.0.0
  srcpkgs/python3-pydot/template
Labels: new-package

#54040 New package: zcfan-1.4.0
  srcpkgs/zcfan/files/README.voidlinux
  srcpkgs/zcfan/files/zcfan/run
  srcpkgs/zcfan/template
Labels: new-package

#55436 New package: blocky-0.26.2
  srcpkgs/blocky/files/blocky/run
  srcpkgs/blocky/template
Labels: new-package

#45459 New package: rust-bacon-3.15.0
  srcpkgs/rust-bacon/template
Labels: new-package

#55725 Delete unixbench package
  srcpkgs/unixbench/patches/install.patch
  srcpkgs/unixbench/template
Labels: remove

#55689 New package: trivy-0.63.0
  srcpkgs/trivy/template
Labels: new-package

#55521 moc: remove package
  srcpkgs/moc/patches/ffmpeg4.patch
  srcpkgs/moc/patches/move-pcm-buffer-to-heap.patch
  srcpkgs/moc/template
  srcpkgs/removed-packages/template
Labels: remove

#55794 xbps: update to 0.60.
  srcpkgs/xbps/patches/fix-transposed-calloc.patch
  srcpkgs/xbps/patches/glibc-2.38.patch
  srcpkgs/xbps/patches/xbps-src-comp.patch
  srcpkgs/xbps/template
Labels: core

#55730 New package: ifupdown-ng-0.12.1
  srcpkgs/ifupdown-ng/patches/fix-tests.patch
  srcpkgs/ifupdown-ng/template
Labels: new-package

#55742 New package: stopmotion-0.9.0
  srcpkgs/stopmotion/patches/nftw-musl.patch
  srcpkgs/stopmotion/template
Labels: new-package

#55815 New package: video-compare-20250420
  srcpkgs/video-compare/template
Labels: new-package

#55884 New package: urusai-1.0.3
  srcpkgs/urusai/template
Labels: new-package

#55879 New package: openhantek-3.4.0
  srcpkgs/openhantek/template
Labels: new-package

#55895 New package: xcaddy-0.4.4
  srcpkgs/xcaddy/template
Labels: new-package

#55900 New Package: lxqt-wayland-session
  srcpkgs/lxqt-wayland-session/template
Labels: new-package
