Repository void-linux/void-packages, pull requests merged in 2025-03, with the labels that each got.

#54471 wine: update to 10.2
  srcpkgs/wine/INSTALL
  srcpkgs/wine/REMOVE
  srcpkgs/wine/files/wine
  srcpkgs/wine/files/wineserver
  srcpkgs/wine/template
Labels: needs-testing

#53355 [BREAKING] strongswan: update to 6.0.0.
  srcpkgs/strongswan/INSTALL.msg
  srcpkgs/strongswan/files/strongswan/run
  srcpkgs/strongswan/patches/0001-fix-musl.patch
  srcpkgs/strongswan/patches/0002-fix-musl.patch
  srcpkgs/strongswan/patches/rm-test_fetch_http.patch
  srcpkgs/strongswan/patches/rm-test_stream.patch
  srcpkgs/strongswan/template
Labels: Stale

#54618 common/build-style/go.sh: disable verbose test output
  common/build-style/go.sh
Labels: xbps-src

#54779 common/shlibs: fix typo
  common/shlibs
Labels: xbps-src

#54790 common/travis/check-install.sh: don't exit after install failure
  common/travis/check-install.sh
Labels: xbps-src
