Repository void-linux/void-packages, pull requests merged in 2025-05, with the labels that each got.

#55222 xbps-src: document -Q non-recursiveness
  xbps-src
Labels: xbps-src

#54784 New package: decibels-48.0
  srcpkgs/decibels/template
Labels: new-package

#54917 New package: adwaita-fonts-48.2.
  srcpkgs/adwaita-fonts/template
Labels: new-package

#49454 New package: wluma-4.9.0
  srcpkgs/wluma/template
Labels: new-package

#53889 New package: Bonzomatic-2023.06.15
  srcpkgs/Bonzomatic/patches/fix-wayland.patch
  srcpkgs/Bonzomatic/template
Labels: new-package

#54488 hooks/pre-pkg/06-verify-python-deps: support alternative packages
  common/scripts/parse-py-metadata.py
Labels: xbps-src

#55276 New package: satty
  srcpkgs/satty/template
Labels: new-package

#54896 New package: openxr-1.1.47
  common/shlibs
  srcpkgs/openxr-devel
  srcpkgs/openxr/template
Labels: new-package

#55355 New package: cameractrls-0.6.7
  srcpkgs/cameractrls/template
Labels: new-package

#52263 ripgrep-all: update to 0.10.9.
  srcpkgs/ripgrep-all/template
Labels: new-package

#53749 pnpm: update to 10.4.1.
  srcpkgs/pnpm/template
Labels: Stale

#53350 runc: update to 1.2.5.
  srcpkgs/runc/template
Labels: Stale
